<section id="home">

    <div class="content-inner">

        <?php

        if ($this->headerBanner) {

            echo $this->showBanner($this->headerBanner, 'headerBanner');

        }

        ?>

        <div id="slider">

        <?php foreach ( $this->featured as $featured ) : ?>

            <div>

                <div class="content-picture">

                    <a href="http://<?php echo $this->baseUrl() . '/' . $featured->uri; ?>" ><div class="picture-frame"></div></a>

                    <img class="picture" src="<?php echo $this->site['assetsPath'] . '/img/capture/' . $featured->codSoftware.'-featured.png' ?>"

                        alt="<?php echo $featured->name ?>">

                </div>

                <div class="content-slide">

                    <div class="slide-wrapper">

                        <div class="slide-inner" style="margin: 0 auto;">

                            <div class="btn-download">

                                    <a href="http://<?php echo $this->baseUrl() . '/' . $featured->uri; ?>" class="uppercase">

                                            <?php echo Zend_Registry::get('tr')->translate('DOWNLOAD') ?>

                                    </a>

                            </div>

                            <h2 class="featured-title">

                                    <a href="http://<?php echo $this->baseUrl() . '/' . $featured->uri; ?>" >

                                            <?php echo $featured->name ?>

                                    </a>

                            </h2>

                            <div class="featured-brief">

                                    <?php echo $featured->brief ?>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

	<?php endforeach; ?>

	</div> <!-- end slide-->

    </div>

</section>



<section id="category">

    <div class="content-inner">

        <div id="content-title-category">

            <h3><?php echo Zend_Registry::get('tr')->translate('CATEGORIES') ?></h3>

	</div>

	<ul>

            <?php echo $this->partialLoop('partials/categories.phtml', $this->categories); ?>

        </ul>

    </div>

    <?php

    if ($this->footerBanner) {

        echo $this->showBanner($this->footerBanner, 'footerBanner');

    }

    ?>	

</section>

	