<section id="main-soft" class="category-page">

    <div   class="content">

        <?php

if ($this->headerBanner) {

    echo '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner').'</div>';

}

?>

<div class="box-left">

    <?php if (count($this->paginator) === 0) : ?>

        <h2><?php echo $this->tr->translate('SOFTWARE NO FOUND IN CATEGORY'); ?></h2>

    <?php else: ?>

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>

        <h2> <?php echo $this->tr->translate('SOFTWARE IN CATEGORY') . " '" . $this->category->category."':"; ?></h2>

        <?php foreach( $this->paginator as $soft ): ?>

            <div class="software border-left">

                <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $soft->codSoftware ?>.png" alt="<?php echo $soft->name ?>">

                <h3><?php echo (strlen($soft->name ) > 10)?substr($soft->name , 0, 10).'...':$soft->name; ?></h3>

                <p><?php echo (strlen( $soft->brief ) > 95)?substr($soft->brief, 0, 95).'...': $soft->brief  ?></p>

                <a href="http://<?php echo $this->urlSite . '/' . $soft->uri; ?>">

                    <?php echo Zend_Registry::get('tr')->translate('DOWNLOAD') ?>

                </a>

            </div>

        <?php endforeach ?>

    <?php endif; ?>

</div>

<div id="category" class="box-right">

    <h2><?php echo Zend_Registry::get('tr')->translate('CATEGORIES') ?></h2>

    <ul>

        <?php echo $this->partialLoop('partials/categories.phtml', $this->categories); ?>

    </ul>

</div>

<div class="clearboth"></div>

<?php

if ($this->footerBanner) {

    echo '<div class="ad">'.$this->showBanner($this->footerBanner, 'footerBanner').'</div>';

}

?>

</section>

