<?php

echo $this->soft->scriptDownloadPage;

if (strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "chrome")) { 

    $instructionsClass = 'instructions-chrome';

    $arrow = 'arrow-chrome';

} elseif (strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "firefox")) {

    $instructionsClass = 'instructions-firefox';

    $arrow = 'arrow-firefox';

} elseif (strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "trident") || strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "msie")) {

    $instructionsClass = 'instructions-explorer';  

    $arrow = 'arrow-explorer';  

} else {

    $instructionsClass = 'instructions-generic';

    $arrow = 'arrow-chrome';

}

?>

<div id="modal"></div>

<div id="instructions" onclick="$(this).hide();$('#modal').hide();">



    <div id="instructions-box" class="<?php echo $instructionsClass ?>">

        <span id="countdown">

            <?php echo $this->tr->translate('Your download will start in')?>

            <span id="countdownNumber">5</span> 

            <?php echo $this->tr->translate('seconds...'); ?>

        </span>

        <span id="again">

            <?php echo $this->tr->translate('If the download does not start, please'); ?>

            <a href="javascript:download('<?php echo $this->downloadUrl ?>', '<?php echo $this->downloadName ?>');"

            id="btn-download"><?php echo $this->tr->translate('click here'); ?></a>

        </span>
        <?php if (strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "chrome")) { ?>
          <div id="step-<?php echo $arrow ?>">
            <img src="<?php echo $this->site['assetsPath'] . '/img/'.$instructionsClass.'.jpg' ?>">
          </div>
        <?php } else { ?>
          <div id="step-<?php echo $arrow ?>">

              <img id="step-arrow-img" src="<?php echo $this->site['assetsPath'] . '/img/'.$arrow.'.png' ?>">&nbsp;

          </div>

          <div id="steps">

              <div id="steps-image">

                  <img src="<?php echo $this->site['assetsPath'] . '/img/'.$instructionsClass.'.png' ?>">

              </div>

              <div class="pasos">

                  <div id="paso1"><?php echo $this->tr->translate('Click Run or Open to begin'); ?></div>

                  <div id="paso2"><?php echo $this->tr->translate('Follow our easy installation wizard'); ?></div>

                  <div id="paso3"><?php echo $this->tr->translate('Enjoy your new software'); ?></div>

              </div>

          </div>
        <?php } ?>

    </div>

</div>



<section id="main" class="landing">





        <input type="hidden" name="downloadUrl" id="downloadUrl" value="<?php echo $this->downloadUrl ?>"/>

        <input type="hidden" name="downloadName" id="downloadName" value="<?php echo $this->downloadName ?>"/>

        <input type="hidden" name="signature" id="signature" value="<?php echo $this->site['signature'] ?>"/>

        <input type="hidden" name="externalBundle" id="externalBundle" value="<?= $this->externalBundle ?>"/>

        <input type="hidden" name="externalBundleUrl" id="externalBundleUrl" value="<?= $this->externalBundleUrl ?>"/>



  <div id="landing" class="content">



    <img src="<?php echo $this->site['assetsPath'] . '/img/icon/' . $this->soft->codSoftware.'.png' ?>"

     alt="<?php echo $this->soft->name ?>">



    <h1><?php echo $this->soft->name ?></h1>

    <h2 class="text-detail"><?php echo $this->soft->brief ?></h2>

 

      <div class="box-left">

          <a href="<?php echo  '/download/'.$this->soft->softwareUri.$this->statKey; ?>" 

            class="btn-landing"> </a>

      </div>



    <div class="clicking">

      <?php if(isset($this->googleQuery)) : ?>

        <p id="googleSearch"><?php echo $this->tr->translate('You have searched for'); ?> "<?php echo $this->googleQuery ?>". </p>

      <?php endif; ?>

        <?php echo $this->downloadInfo; ?>

    </div>

  </div>

</section>





<section id="main-detail">

    <div  class="content">

        

        <div class="box-left">



            <h2><?php echo $this->tr->translate('SOFTWARE REVIEW') ?></h2>

            <div class="soft-detail">

                <?php echo $this->site['name'] . $this->tr->translate('is not an official partner or reseller of') . ' ' . $this->soft->developer . $this->tr->translate("'s products") ?>.

                <?php echo $this->soft->detail ?>

            </div>



              <div class="box-left">

                  <a href="<?php echo  '/download/'.$this->soft->softwareUri.$this->statKey; ?>" 

                    class="btn-landing"> </a>

              </div>



        </div>

        <div id="screens" class="box-right">



            <h2><?php echo $this->tr->translate('SCREENSHOTS') ?></h2>

            <aside class="figures">

                <figure>

                   <img width="200" src="<?php echo $this->site['assetsPath']?>/img/capture/<?php echo $this->soft->codSoftware ?>.jpg" alt="<?php echo $this->soft->name ?>" />

               </figure>

               <?php if (file_exists( $this->site['assetsPath'] . '/img/capture/' . $this->soft->codSoftware . '_1.jpg')) : ?>

                 <figure>

                     <img width="200" src="<?php echo $this->site['assetsPath']?>/img/capture/<?php echo $this->soft->codSoftware ?>_1.jpg" alt="<?php echo $this->soft->name ?>" />

                 </figure>

               <?php endif ?>



              <?php if (file_exists( $this->site['assetsPath'] . '/img/capture/' . $this->soft->codSoftware . '_2.jpg')) : ?>

               <figure>

                   <img width="200" src="<?php echo $this->site['assetsPath']?>/img/capture/<?php echo $this->soft->codSoftware ?>_2.jpg" alt="<?php echo $this->soft->name ?>" />

               </figure>

              <?php endif; ?>

            </aside>

        </div>



       <div class="clearboth"></div>

     </div>

</section>

<aside id="main-toolbar">

    <div class="content">    

        <div id="toolbar">

          <div id="toolbarText"><?php echo $this->toolbar; ?></div>

          <div id="toolbarImg"></div>

          <div class="clear"></div>

       </div>

       <div class="clearboth"></div>

    </div>

</aside>

