    <?php /*
    if ($this->headerBanner) {
        echo $this->showBanner($this->headerBanner, 'headerBanner');
    }
    ?>
    <div class="center-search">
        <div class="container-messages">
            <div class="message">
                <span>
                    
                </span>
            </div>
        </div>
        <div class="container-messages">
            <div class="message">
                <span>
                    
                </span>
            </div>
        </div>
        <div class="container-messages">
            <div class="message">
                <span>
                    <?php echo $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?>
                    <span class="black"><?php echo $this->tr->translate('RECOMENDED SOFTWARE') ?>:</span>
                </span>
            </div>
        </div>
        <div class="list-soft promoted">
            <ul class="front-list">
                <?php foreach( $this->list as $soft ): ?>
                <li>
                    <div class="soft">
                        <div class="soft-icon">
                            <a href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>">
                                <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $soft->codSoftware ?>.png" 
                                     width="64" height="64"  alt="<?php echo $soft->name ?>" />
                            </a>
                        </div>
                        <div class="soft-item">
                            <div class="soft-name black">
                                <a href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>" class="uppercase">
                                    <?php 
                                    echo $soft->name
                                    ?>
                                </a>
                            </div>
                            <div class="soft-brief black">
                                <?php echo $soft->brief ?>
                            </div>
                            <div class="soft-download-btn black">
                                <a class="btn-download-small" href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>" class="uppercase">
                                    <?php 
                                    echo Zend_Registry::get('tr')->translate('DOWNLOAD') 
                                    ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
    <?php
    if ($this->rightBanner) {
        echo $this->showBanner($this->rightBanner, 'rightBanner');
    }
    ?>
</div> <!-- end contaiener-->
		<div id="footer-download">
			<div class="container">
				<h2 class="Light title-tab">
                    <?php echo Zend_Registry::get('tr')->translate('TOP DOWNLOADS') ;?>
                </h2>

				<div id="slide-footer">
					<ul class="list-software">
					
						<?php 
						$nl = 0;
						foreach ($this->topDownloads as $softTop) { ?>
							
							<?php echo ($nl == 0)?'<li>':''; ?>
									<div class="soft black">
							        <div class="soft-icon">
							            <a href="http://<?php echo $softTop->uri . '.' . $this->urlSite ?>">
							                <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $softTop->codSoftware ?>.png" 
							                     width="64" height="64"  alt="<?php echo $soft->name ?>" />
							            </a>
							        </div>
							        <div class="soft-item">
							            <div class="soft-name">
							                <a href="http://<?php echo $softTop->uri . '.' . $this->urlSite ?>" class="uppercase">
							                    <?php 
							                    $name = (strlen($softTop->name) > 20)?substr($softTop->name, 0, 20).'...':$softTop->name;
							                    echo $name;
							                    ?>
							                </a>
							            </div>
							           
							            <div class="soft-download-btn">
							                <a class="btn-download-small" href="http://<?php echo $softTop->uri . '.' . $this->urlSite ?>" class="uppercase">
							                    <?php 
							                    echo Zend_Registry::get('tr')->translate('DOWNLOAD') ;
							                    ?>
							                </a>
							            </div>
							        </div>
							    </div>
							    
							<?php if($nl == 1)
							{ 
								echo '</li>'; 
								$nl = 0;

							 }else{
							 	$nl++;
							 }
						?>


						<?php } ?>

		        
				</ul>
					
			</div> <!--  end slider footer -->
					<div class="footer-nav">
						<a href="#" id="prev-f"><</a> 
	       				 <a href="#" id="next-f">></a>
	       			</div>
                                <?php
                                if ($this->footerBanner) {
                                    echo $this->showBanner($this->footerBanner, 'footerBanner');
                                }
                                ?>
					

			</div> <!-- end  contentainer -->

*/ ?>
<section id="main-soft" class="category-page">
    <div   class="content">
        <?php
if ($this->headerBanner) {
    echo $this->showBanner($this->headerBanner, 'headerBanner');
}
?>
<div class="box-left">
        <h2><?php echo $this->tr->translate('THE SOFTWARE IS NOT FOUND') ?>.
            <?php echo $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?>
            <?php echo $this->tr->translate('RECOMENDED SOFTWARE') ?>:</h2>
        <?php foreach( $this->list as $soft ): ?>
            <div class="software border-left">
                <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $soft->codSoftware ?>.png" alt="<?php echo $soft->name ?>">
                <h3><?php echo (strlen($soft->name ) > 10)?substr($soft->name , 0, 10).'...':$soft->name; ?></h3>
                <p><?php echo (strlen( $soft->brief ) > 95)?substr($soft->brief, 0, 95).'...': $soft->brief  ?></p>
                <a href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>">
                    <?php echo Zend_Registry::get('tr')->translate('DOWNLOAD') ?>
                </a>
            </div>
        <?php endforeach ?></div>
<div id="category" class="box-right">
    <h2><?php echo Zend_Registry::get('tr')->translate('CATEGORIES') ?></h2>
    <ul>
        <?php echo $this->partialLoop('partials/categories.phtml', $this->categories); ?>
    </ul>
</div>
<div class="clear"></div>
<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>
</section>