<div class="left">

	<div id="categories">
	    <h3 class="uppercase"><?php echo $this->tr->translate('Categories') ?></h3>
	    <ul>
			<?php echo $this->partialLoop('partials/categories.phtml', $this->categories); ?>
	    </ul>
		<div id="categories-footer"></div>
	</div>

	<div id="search-cloud">
	    <h3 class="uppercase"><?php echo $this->tr->translate('Top Searches') ?></h3>
	    <div class="tags">
	        <ul>
				<?php echo $this->partialLoop('partials/search-cloud.phtml', $this->terms); ?>
	        </ul>
			<div id="search-cloud-bottom"></div>
	    </div>
	</div>

</div>

<div class="right">
	<div class="center-search">
		<div id="order-box">
	      <p><?php echo $this->tr->translate('Sort By'); ?></p>
	        <a href="http://<?php echo $this->url(array('order' => 'name'))?>" <?php echo ($this->varOrder=='name' || $this->varOrder=='')?'class="active"':'';?>><?php echo $this->tr->translate('Name'); ?></a>
	        <a href="http://<?php echo $this->url(array('order' => 'downloads'))?>" <?php echo ($this->varOrder=='downloads')?'class="active"':'';?>><?php echo $this->tr->translate('Downloads'); ?></a>
	        <a href="http://<?php echo $this->url(array('order' => 'rating'))?>" <?php echo ($this->varOrder=='rating')?'class="active"':'';?>><?php echo $this->tr->translate('Rating'); ?></a>
	     </div>
		    <?php if ($this->hot): ?>
				<div class="container-messages">
			        <div class="message">
			            <span>
			            	<?php echo $this->tr->translate('NO_SEARCH_RESULTS_FOR') ?>
			            </span>
			            <span class="not-found">"<?php echo $this->search ?>"</span>
			        </div>
				</div>

				<div class="container-suggetions">
					<h4><?php echo $this->tr->translate('SUGGESTIONS') ?></h4>
					<ul>
						<li>
							<?php echo $this->tr->translate('MAKE_SURE_THAT_EVERYTHING_IS') ?>
							<span><?php echo $this->tr->translate('SPELLED_CORRECTLY') ?></span>
						</li>
						<li>
							<?php echo $this->tr->translate('TRY_TO_USE') ?>
							<span><?php echo $this->tr->translate('DIFERENT_OR_MORE_GENERAL_KEYWORDS') ?></span>
						</li>
						<li>
							<?php echo $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?>
							<span><?php echo $this->tr->translate('RECOMENDED SOFTWARE') ?>:</span>
						</li>
					</ul>
		            <span class="others"></span>
		        </div>
		    <?php else : ?>
		    	<div class="container-messages">
			        <div class="message">
			            <span>
			            	<?php echo $this->tr->translate('SEARCH_RESULTS_FOR') ?>
			            </span>
			            <span class="not-found">"<?php echo $this->search ?>"</span>
			        </div>
				</div>
		    <?php endif; ?>
		<div class="list-soft promoted" id="list-new">
			<ul class="front-list">
            <?php foreach( $this->paginator as $soft ): ?>
				<li>
					<div class="soft-item">
					    <a href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>" class="uppercase">
					        <?php echo $soft->name ?>
					    </a>
					    <span class="brief">
					        <?php echo $soft->brief ?>
					    </span>
					    <span class="rating rating-<?php echo (ceil($soft->rating/2)) ?>">
                                            </span>
				        <span class="total-download">
				    		<span class="title"><?php echo Zend_Registry::get('tr')->translate('TOTAL DOWNLOADS') ?> :</span>
				    		<?php echo $soft->downloads ?>
				    	</span>

					</div>
					<div class="icon">
					    <a href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>">
					        <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $soft->codSoftware ?>.png" width="64" height="64"  alt="<?php echo $soft->name ?>" />
					    </a>
					</div>
					<div class="download-btn clear">
					    <a class="btn-download-small" href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>"></a>
					</div>
				</li>
            <?php endforeach ?>
			</ul>
        </div>
        <div class="row paginator-box">
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>
        </div>
		<div class="clear"></div>

    </div>


	<div id="top-download">
		<h3 class="uppercase"><?php echo $this->tr->translate('Top Downloads') ?></h3>

		<ul>
			<?php echo $this->partialLoop('partials/top-downloads.phtml', $this->topDownloads); ?>
		</ul>
	</div>
	<div id="top-download-footer"></div>
</div>

<div class="clear"></div>