<?php
echo $this->software->scriptThankyouPage;
?>
<section id="main-soft" class="category-page">
    <div   class="content">
        <?php
    if ($this->headerBanner) {
        echo $this->showBanner($this->headerBanner, 'headerBanner');
    }
    ?>
        <div class="box-left">
            <h2>
                <?php echo $this->tr->translate('THANK YOU PAGE'); ?>
                <span class="black">"<?php echo $this->software->name ?>"</span>
            </h2>
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>

    <?php foreach( $this->paginator as $soft ): ?>

            <div class="software border-left">
                <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $soft->codSoftware ?>.png" alt="<?php echo $soft->name ?>">
                <h3><?php echo (strlen($soft->name ) > 10)?substr($soft->name , 0, 10).'...':$soft->name; ?></h3>
                <p><?php echo (strlen( $soft->brief ) > 95)?substr($soft->brief, 0, 95).'...': $soft->brief  ?></p>
                <a href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>">
                    <?php echo Zend_Registry::get('tr')->translate('DOWNLOAD') ?>
                </a>
            </div>
    <?php endforeach ?>
             
    </div>
     
        <div id="category" class="box-right">
            <h2><?php echo Zend_Registry::get('tr')->translate('CATEGORIES') ?></h2>
            <ul>
                <?php echo $this->partialLoop('partials/categories.phtml', $this->categories); ?>
            </ul>
        </div>
    </div>
<div class="clear"></div>
<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>
</section>
<!-- Facebook Conversion Code for Obaport -->
<script>(function() {
var _fbq = window._fbq || (window._fbq = []);
if (!_fbq.loaded) {
var fbds = document.createElement('script');
fbds.async = true;
fbds.src = '//connect.facebook.net/en_US/fbds.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(fbds, s);
_fbq.loaded = true;
}
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6027690901004', {'value':'0.00','currency':'ARS'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6027690901004&amp;cd[value]=0.00&amp;cd[currency]=ARS&amp;noscript=1" /></noscript>