<?php 

echo $this->soft->scriptLandingPage;

if(!$this->platform['isMobile'] && !$this->platform['isOSX']) : ?>

  <section id="main" class="landing">

<?php else: ?>

  <section id="main-mobile" class="landing">

<?php endif; ?>



  <div id="landing" class="content">



    <img src="<?php echo $this->site['assetsPath'] . '/img/icon/' . $this->soft->codSoftware.'.png' ?>"

     alt="<?php echo $this->soft->name ?>">



    <h1><?php echo $this->soft->name ?></h1>

    <h2 class="text-detail"><?php echo $this->soft->brief ?></h2>





    <?php if($this->platform['isWindows']): ?> 

      <div class="box-left">

          <a href="<?php echo '/download/'.$this->soft->softwareUri.$this->statKey; ?>" 

            class="btn-landing"> </a>

      </div>

    <?php endif; ?>



    <div id="incognitoMsg">

      Unfortunately the software you're looking for is not available for download in "Incognito Mode" due to our security policies. <br/>

      Please go to the <a href="<?php echo $this->soft->developerWeb ?>">developer's site</a> to get this software for free.

    </div>



    <div class="clicking">

      <?php if(isset($this->googleQuery)) : ?>

        <p id="googleSearch"><?php echo $this->tr->translate('You have searched for'); ?> "<?php echo $this->googleQuery ?>". </p>

      <?php endif; ?>

        <?php if($this->platform['isWindows']) echo $this->downloadInfo; ?>

    </div>

  </div>

</section>





<section id="main-detail">

    <div  class="content">

        <?php

        if ($this->headerBanner) {

            echo $this->showBanner($this->headerBanner, 'headerBanner');

        }

        ?>

        <div class="box-left">



            <?php if(!$this->platform['isWindows']): ?> 

              <div class="mobile">

                  <?php echo (isset($this->banner->mobileMonetization)) ? $this->banner->mobileMonetization : '' ;?>

              </div>

            <?php endif; ?>



            <h2><?php echo $this->tr->translate('SOFTWARE REVIEW') ?></h2>

            <div class="soft-detail">

                <?php echo $this->site['name'] . $this->tr->translate('is not an official partner or reseller of') . ' ' . $this->soft->developer . $this->tr->translate("'s products") ?>.

                <?php echo $this->soft->detail ?>

            </div>



            <?php if($this->platform['isWindows']): ?> 

              <div class="box-left">

                  <a href="<?php echo '/download/'.$this->soft->softwareUri.$this->statKey; ?>" 

                    class="btn-landing"> </a>

              </div>

            <?php endif; ?>



        </div>

        <div  class="box-right">

          <div id="screens">

            <h2><?php echo $this->tr->translate('SCREENSHOTS') ?></h2>

            <aside class="figures">

                <figure>

                   <img width="200" src="<?php echo $this->site['assetsPath']?>/img/capture/<?php echo $this->soft->codSoftware ?>.jpg" alt="<?php echo $this->soft->name ?>" />

               </figure>

               <?php if (file_exists( $this->site['assetsPath'] . '/img/capture/' . $this->soft->codSoftware . '_1.jpg')) : ?>

                 <figure>

                     <img width="200" src="<?php echo $this->site['assetsPath']?>/img/capture/<?php echo $this->soft->codSoftware ?>_1.jpg" alt="<?php echo $this->soft->name ?>" />

                 </figure>

               <?php endif ?>



              <?php if (file_exists( $this->site['assetsPath'] . '/img/capture/' . $this->soft->codSoftware . '_2.jpg')) : ?>

               <figure>

                   <img width="200" src="<?php echo $this->site['assetsPath']?>/img/capture/<?php echo $this->soft->codSoftware ?>_2.jpg" alt="<?php echo $this->soft->name ?>" />

               </figure>

              <?php endif; ?>

            </aside>

            </div>

            <?php

        if ($this->rightBanner) {

            echo '<div class="ad">' . $this->showBanner($this->rightBanner, 'rightTopBanner') .'</div>';

        }

        ?>

       

        </div>

        <div class="clearboth"></div>

        <?php

       if ($this->footerBanner) {

          echo '<div class="ad">' .$this->showBanner($this->footerBanner, 'footerBanner').'</div>';

       }

       ?>

       

     </div>

</section>

<aside id="main-toolbar">

    <div class="content">    

        <div id="toolbar">

          <div id="toolbarText"><?php echo $this->toolbar; ?></div>

          <div id="toolbarImg"></div>

          <div class="clear"></div>

       </div>

       <div class="clearboth"></div>

    </div>

</aside>

