<!DOCTYPE html>
<html lang="<?= $this->param('langCode') ?>">

    <head>
        <!-- Meta -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?= $this->meta() ; ?>

        <!-- Title -->
        <?= $this->title(); ?>

        <!-- Assets -->
        <?= $this->asset('site.css'); ?>
        <?= $this->asset('img/favicon.ico', array('rel' => 'icon')); ?>
        <link href="http://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
        <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" />

        <!-- Fallback -->
        <!--[if lt IE 10]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

        <?php echo $this->headScript()->appendFile($this->site['assetsPath'] . '/js/analytics.js') ?>
    </head>

    <body>
        <header class="masthead">
            <div class="container">
                <h1 class="masthead__logo">
                    <a href="<?= $this->link(); ?>">
                        <img src="<?= $this->image('logo.png'); ?>" alt="<?= $this->param('name'); ?>" width="260" height="61" />
                    </a>
                </h1>
                <nav class="masthead__navigation">
                    <ul>
                        <?= $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
                    </ul>
                </nav>
            </div>
        </header>
        <!-- END .masthead -->

        <div class="mastcontent">
            <?= $this->layout()->content; ?>
        </div>
        <!-- END .mastcontent -->

        <footer class="mastfoot">
            <div class="container">
                <nav class="mastfoot__navigation">
                    <ul>
                        <?= $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>   
                        <li><a href="<?= $this->link('index/sitemap'); ?>">Sitemap</a></li>
                        <li class="copyright">&copy; <?= $this->action('index', 'content', null, array('section' => 'BOTTOM-LINE')); ?></li>
                    </ul>
                </nav>
                <!-- END .mastfoot__navigation -->
                
                <div class="mastfoot__disclaimer">
                    <?= $this->action('index', 'content', null, array('section' => 'DISCLAIMER')); ?>
                </div>
                <!-- END .mastfooter__disclaimer -->
            </div>
        </footer>
        <!-- END .mastfoot -->
        
        <!-- Scripts -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>
        <?= $this->script('js/main.min.js'); ?>
        <?= $this->script(array('../common/js/jquery.cycle.min.js', '../common/js/main.min.js')); ?>
        <input type="hidden" id="template" value="LastShoot" />
        <script>
            $(document).ready(function(){if($(".cycleSlider").size!=0){$(".cycleSlider").cycle({fx:"fade",prev:".slider__controls__prev",next:".slider__controls__next",delay:-5e3,pagerAnchorBuilder:function(e,t){return'<a href="#"> </a>'}})}})
        </script>

    </body>
</html>
<!-- <?= $this->param('name'); ?> -->