<!DOCTYPE html>
<html lang="<?= $this->param('langCode') ?>">

    <head>
        <!-- Meta -->
        <?= $this->meta() ; ?>

        <!-- Title -->
        <?= $this->title(); ?>

        <!-- Assets -->
        <?= $this->asset('main.min.css'); ?>
        <?= $this->asset('img/favicon.ico', array('rel' => 'icon')); ?>

        <!-- Fallback -->
        <!--[if IE 9]><link href="<?= $this->site['assetsPath'] . '/css/main_ie9.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 6]><link href="<?= $this->site['assetsPath'] . '/css/main_ie6.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 7]><link href="<?= $this->site['assetsPath'] . '/css/main_ie7.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if lt IE 10]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<script src="http://ads.adficubed.com/js_generados/adfi_553a55526d338.js" type="text/javascript"></script>
        <?php echo $this->headScript()->appendFile($this->site['assetsPath'] . '/js/analytics.js') ?>
    </head>

	<body>

		<div id="wrapper">
			<div class="container">
				<header>
					<div id="search">
						<form id="searchForm" action="http://<?= $this->baseUrl();?>/software/search" 
							method="get" name="searchForm">
							<input id="searchText" type="text" value="" name="search" />
							<input type="submit" id="b-search" value="" />
						</form>
					</div>
					<div id="logo" onclick="location.href='http://<?= $this->baseUrl() ?>'">

					</div>
				</header>

				<nav id="top-menu">
					<ul>
						<?= $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
					</ul>
				</nav>

				<div>
					<?= $this->layout()->content; ?>
				</div>

				<div id="bottom-line">
					<div id="bottom-text">
						<?=  $this->action('index', 'content', null, array('section' => 'BOTTOM-LINE')); ?>
					</div>
					<div id="menu">
						<ul>
							<?= $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
						</ul>
					</div>
				</div>

				<footer id="footer">
					<?= $this->action('index', 'content', null, array('section' => 'DISCLAIMER')); ?>
				</footer>

			</div>
		</div>
        
        <!-- Scripts -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>
        <?= $this->script(array('../common/js/jquery.cycle.min.js', '../common/js/main.min.js')); ?>
        <input type="hidden" id="template" value="Static205" />

    </body>
</html>
<!-- <?= $this->param('name'); ?> -->