<!DOCTYPE html>
<html lang="<?php echo $this->param('langCode') ?>">

    <head>
        <!-- Meta -->
        <?php echo $this->meta() ; ?>

        <!-- Title -->
        <?php echo $this->title(); ?>

        <!-- Assets -->
        <?php echo $this->asset('main.min.css'); ?>
        <?php echo $this->asset('software.min.css'); ?>
        <?php echo $this->asset('modal.css'); ?>
        <?php echo $this->asset('img/favicon.ico', array('rel' => 'icon')); ?>
         <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
        <!-- Fallback -->
        <!--[if IE 9]><link href="<?php echo $this->site['assetsPath'] . '/css/main_ie9.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 6]><link href="<?php echo $this->site['assetsPath'] . '/css/main_ie6.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 7]><link href="<?php echo $this->site['assetsPath'] . '/css/main_ie7.css' ?>" rel="stylesheet"><![endif]-->
        <!--[if lt IE 10]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

        <?php echo $this->headScript()->appendFile($this->site['assetsPath'] . '/js/analytics.js') ?>

	</head>

  	<body <?php echo $this->bodyClass; ?>>

	    <div id="wrapper">
	        <div class="container">
	            <header id="header-software">
	          	
			        <nav id="software-top-menu">
						<ul>
			            	<?php echo $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
						</ul>
			        </nav>
						
					<div id="logo-slim" onclick="location.href='http://<?php echo $this->baseUrl()?>'">
						
					</div>
					
	            </header>
					

				<?php echo $this->layout()->content ?>


	            <div id="bottom-line">
	                <div id="bottom-text">
					    <?php echo  $this->action('index', 'content', null, array('section' => 'BOTTOM-LINE')); ?>
					</div>
					<div id="menu">
    					<ul>
    		            	<?php echo $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
    					</ul>
					</div>
				</div>

				<div id="breadcrumbs">
				    <a href="http://<?php echo $this->baseUrl() ?>"><?php echo Zend_Registry::get('tr')->translate('Home') ?></a> / 
				    <a href="http://<?php echo $this->baseUrl() ?>/software/category/uri/<?php echo $this->soft->categoryUri ?>">
				    <?php echo $this->soft->category ?></a>
				</div>

		        <div id="bottom-menu" >
		            <ul id="quad">
		                <?php echo $this->partialLoop('partials/software-categories.phtml', $this->categories); ?>
		            </ul>
				</div>

				<footer id="footer" >
	                <?php echo $this->action('index', 'content', null, array('section' => 'DISCLAIMER')); ?>
	            </footer>
	        </div>
	    </div>
                
        <!-- Scripts -->
       

        <?= $this->headScript(); ?>
        <?php echo $this->script(array('../common/js/jquery.cycle.min.js', '../common/js/main.min.js', '/js/browserdetector.js', '/js/jquery-ui.custom.min.js')); ?>
        <?php echo $this->partial('partials/arrow.phtml'); ?>

        <input type="hidden" id="template" value="Static205" />
    </body>
</html>
<!-- <?php echo $this->param('name'); ?> -->