<div class="container">
    <div class="page arial">
        <?php if ( isset($this->form) ) echo $this->form ?>

        <?php if ( isset($this->successMail) ): ?>
                <div class="message">
                        <span> <?= $this->successMail ?></span>
                </div>
        <?php endif ?>
    </div>
</div>
<section id="category" class="white">
        <div class="container">
            <h3><?= Zend_Registry::get('tr')->translate('CATEGORIES') ?></h3>
            <ul>
                <?= $this->partialLoop('partials/categories.phtml', $this->categories); ?>
            </ul>
        </div>
</section>

<section class="page">
    <div class="container">
        <div class="page__404">
        <?php if ( isset($this->form) ) echo $this->form ?>

        <?php if ( isset($this->successMail) ): ?>
        <div class="notification notification--success">
                <span> <?= $this->successMail ?></span>
        </div>
        <?php endif ?>
        </div>
    </div>
</section>
<!-- END .page -->

<?= $this->partial('partials/categories.phtml', array('categories' => $this->categories)); ?>