    <?php
    if ($this->headerBanner) {
        echo $this->showBanner($this->headerBanner, 'headerBanner');
    }
    ?>
    <div class="page">
        <?php echo $this->action('index', 'content', null, array('section' => 'ERROR_MSG')); ?>
    </div>
</div> <!-- end contaiener-->
		<div id="footer-download">
			<div class="container">
				<h2 class="Light title-tab"><?php echo Zend_Registry::get('tr')->translate('TOP DOWNLOADS') ;?></h2>

				<div id="slide-footer">
					<ul class="list-software">
					
						<?php 
						$nl = 0;
						foreach ($this->topDownloads as $softTop) { ?>
							
							<?php echo ($nl == 0)?'<li>':''; ?>
									<div class="soft black">
							        <div class="soft-icon">
							            <a href="http://<?php echo $softTop->uri . '.' . $this->urlSite ?>">
							                <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $softTop->codSoftware ?>.png" 
							                     width="64" height="64"  alt="<?php echo $soft->name ?>" />
							            </a>
							        </div>
							        <div class="soft-item">
							            <div class="soft-name">
							                <a href="http://<?php echo $softTop->uri . '.' . $this->urlSite ?>" class="uppercase">
							                    <?php 
							                    $name = (strlen($softTop->name) > 20)?substr($softTop->name, 0, 20).'...':$softTop->name;
							                    echo $name;
							                    ?>
							                </a>
							            </div>
							           
							            <div class="soft-download-btn">
							                <a class="btn-download-small" href="http://<?php echo $softTop->uri . '.' . $this->urlSite ?>" class="uppercase">
							                    <?php 
							                    echo Zend_Registry::get('tr')->translate('DOWNLOAD') ;
							                    ?>
							                </a>
							            </div>
							        </div>
							    </div>
							    
							<?php if($nl == 1)
							{ 
								echo '</li>'; 
								$nl = 0;

							 }else{
							 	$nl++;
							 }
						?>


						<?php } ?>

		        
				</ul>
					
			</div> <!--  end slider footer -->
					<div class="footer-nav">
						<a href="#" id="prev-f"><</a> 
	       				 <a href="#" id="next-f">></a>
	       			</div>
				<?php
                                if ($this->footerBanner) {
                                    echo $this->showBanner($this->footerBanner, 'footerBanner');
                                }
                                ?>
					

			</div> <!-- end  contentainer -->