<?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>

<div class="main main--page">
    <?php echo $this->partial('partials/sidebar.phtml', array(
        'titles' => array(
            'categories' => $this->tr->translate('Categories'),
            'terms' => $this->tr->translate('Top Searches'),
            ),
        'data' => array(
            'categories' => $this->categories,
            'terms' => $this->terms,
            ),
        'banners' => array(
            'leftBottomBanner' => $this->leftBottomBanner ? $this->showBanner($this->leftBottomBanner, 'leftBottomBanner') : false
            )
    )); ?>

	<section class="page">

		<?php if($this->image): ?>
		<figure class="page__image">
			<img src="<?php echo $this->image; ?>" alt="<?php echo $this->title;?>" />
		</figure>
		<?php endif; ?>

		<h2 class="page__title"><?php echo $this->title; ?></h2>

		<div class="page__content">
			<?php echo $this->content; ?>
		</div>

	</section>
	<!-- END .page -->
</div>
<!-- END .content -->

<?php echo $this->footerBanner ? '<div class="ad">' . $this->showBanner($this->footerBanner, 'headerBanner') . '</div>' : ''; ?>