<!-- todo viene dentro de un div que se abre en el layout -->
    <?php 
    echo $this->soft->scriptLandingPage;
    if ( isset($this->googleQuery) ) { 
    ?>
    <p id="googleSearch"><?php echo $this->tr->translate('You have searched for'); ?> "<?php echo $this->googleQuery ?>" </p>
    <?php } ?>
    <div id="slider">
        <div>
            <div class="content-box left">
                <h1 class="text-1 Light">
                    <?php echo $this->soft->name ?>
                </h1>
                <p class="text-3 Regular">
                    <h2><?php echo $this->soft->brief ?></h2>
                </p>
                <?php if($this->platform['isWindows']): ?>
                    <a href="<?php echo '/download/'.$this->uri.$this->statKey; ?>" class="btn-download">
                        <span class="t-dw black">
                            <span class="text-btn-dw"><?php echo Zend_Registry::get('tr')->translate('DOWNLOAD') ?> 
                                <span><?php echo Zend_Registry::get('tr')->translate('100% SAFE DOWNLOAD') ?></span>
                            </span>
                        </span>
                    </a>
                <?php endif; ?>
            </div>
            <div class="content-box left">

                <?php if($this->platform['isWindows']): ?>

                    <div id="content-img"></div>
                    <img width="430" height="298" src="<?php echo $this->site['assetsPath']?>/img/capture/<?php echo $this->soft->codSoftware ?>.jpg" alt="<?php echo $this->soft->name ?>" />

                    <?php if(file_exists("img/capture/{$this->soft->codSoftware}_2.jpg")):?>
                        <img width="430" height="298" src="<?php echo $this->site['assetsPath'] ?>/img/capture/<?php echo $this->soft->codSoftware ?>_2.jpg" alt="<?php echo $this->soft->name ?>" />
                    <?php endif; ?>

                    <?php if(file_exists("img/capture/{$this->soft->codSoftware}_3.jpg")): ?>
                        <img width="430" height="298" src="<?php echo $this->site['assetsPath'] ?>/img/capture/<?php echo $this->soft->codSoftware ?>_3.jpg" alt="<?php echo $this->soft->name ?>" />
                    <?php endif; ?>

                <?php else: ?>

                    <div id="download-btn-container" class="banners">
                        <?php echo (isset($this->banner->mobileMonetization)) ? $this->banner->mobileMonetization : '' ;?>
                        <span id="download-btn-big" style="display:none;"></span>
                    </div>

                <?php endif; ?>
            </div>
        </div>
    </div> <!-- end slide-->

    <?php
    if ($this->headerBanner) {
        echo $this->showBanner($this->headerBanner, 'headerBanner');
    }
    ?>
    <div id="advice">
        <?php
        if($this->platform['isWindows']){ 
            echo $this->downloadInfo;
        }
        ?>
    </div>
    <div class="header-list Regular">
            <a href="#" class="title-tab-details left Light"><span><?php echo $this->tr->translate('SOFTWARE REVIEW') ?></span></a>
            <?php
            if ($this->rightBanner) {
                echo $this->showBanner($this->rightBanner, 'rightBanner');
            }
            ?>
            <?php echo $this->site['name'] . $this->tr->translate('is not an official partner or reseller of') . ' ' . $this->soft->developer . $this->tr->translate("'s products") ?>.
            <?php echo $this->soft->detail ?>
    </div>
	
</div> <!-- end contaiener-->

<div id="footer-download">

    <div class="container">
        <?php if (count($this->comments)) { ?>
            <h2 class="Light title-tab"><?php echo $this->tr->translate('TESTIMONIALS') ?></h2>
            <div id="slide-footer">
                <ul class="list-software comment">
                    <?php 
                    $nl = 0;
                    foreach ($this->comments as $comment) {
                        echo ($nl == 0)?'<li>':''; 
                        ?>
                        <div class="soft black">
                            <div class="soft-icon">
                                <img src="<?php echo $this->site['assetsPath'] ?>/img/comment.png" 
                                          alt="<?php echo $this->soft->name ?>" />
                            </div>
                            <div class="soft-item">
                                <div class="soft-name">
                                    <?php echo $comment->title ?>
                                </div>

                                <div class="Regular">
                                    <?php echo $this->tr->translate('By').' '.$comment->user ?>
                                </div>
                                <div class="soft-brief Regular">
                                    <?php echo $comment->comment ?>
                                </div>
                            </div>
                        </div>

                        <?php if($nl == 1)
                        {
                            echo '</li>'; 
                            $nl = 0;
                        } else {
                             $nl++;
                        }
                    }
                    ?>
                </ul>
            </div> <!--  end slider footer -->	
            <div class="footer-nav <?php echo (count($this->comments)<3)?'off':''; ?>">
                <a href="#" id="prev-f"><</a> 
                <a href="#" id="next-f">></a>
            </div>
        <?php
        }
        if ($this->footerBanner) {
            echo $this->showBanner($this->footerBanner, 'footerBanner');
        }
        ?>
	<div id="toolbar">
            <img src="<?php echo $this->site['assetsPath'] ?>/img/toolbar.png" alt="toolbar image" width="289" height="20" />
            <div id="toolbarText"><?php echo $this->toolbar; ?></div>
        </div>
    </div> <!-- end  contentainer -->