

<li>

	<div class="icon">

		<a class="name" href="http://<?php echo $this->baseUrl() . '/' . $this->uri; ?>">

			<img src="<?php echo $this->partialLoop()->view->site['assetsPath'] ?>/img/icon/<?php echo $this->codSoftware ?>.png" width="48" height="48" alt="<?php echo $this->name ?>"/>

		</a>

	</div>

    <div class="name">

        <a class="name" href="http://<?php echo $this->baseUrl() . '/' . $this->uri; ?>">

    		<?php echo $this->name ?>

    	</a>

    </div>

	<div class="download-btn-lite">

		<a class="btn-download-icon" href="http://<?php echo $this->baseUrl() . '/' . $this->uri; ?>"></a>

	</div>



</li>

