<?php echo $this->soft->scriptDownloadPage; ?>

<?php
if (strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "chrome")) { 
    $image = 'chrome';
} elseif (strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "firefox")) {
    $image = 'firefox';
} elseif (strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "trident") || strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "msie")) {
    $image = 'explorer';    
} else {
    $image = 'generic';
}
?>
<input type="hidden" id="baseUri" value="<?= $this->baseUrl(); ?>">
<?php
if ($this->headerBanner) {
    echo $this->showBanner($this->headerBanner, 'headerBanner');
}
?>

<section class="main">
    <div class="container">
        <div class="content">
            
            <article class="center">
                <div class="soft">
                  <div class="encabezado"> 
                    <div class="wrapper"> 
                      <div class="container_img"> 
                        <div class="container_img_icon"> 
                          <img src="<?= $this->site['assetsPath'] ?>/img/icon/<?= $this->soft->codSoftware ?>.png" alt="<?= $this->soft->name; ?>" height="79" width="79"> 
                        </div> 
                        <div class="container_title"> 
                          <div class="container_title_h2"> 
                            <h2><?= $this->soft->name; ?></h2> 
                          </div> 
                          
                        </div> 
                      </div> 
                    </div> 
                    <span class="spanDownloading"><?= $this->tr->translate('Thanks for downloading')?></span>
                  </div>                  
                    
                    <div class="procedimiento">
                        <span class="spanTitle"><?= $this->tr->translate('Follow these steps to install')?></span>
                        
                        <div class="paso">
                            <ol>
                                <li class="number">1</li>
                                <li><img src="<?= $this->site['assetsPath'] ?>/img/<?= $image ?>.png"></li>
                                <li class="descripcion"><?= $this->tr->translate('CLICK_THE_BUTTON')?>
                                </li>
                            </ol> 
                        </div>
                        <div class="paso">
                            <ol>
                                <li class="number">2</li>
                                <li><img src="<?= $this->site['assetsPath'] ?>/img/paso.2.png"></li>
                                <li class="descripcion"><?= $this->tr->translate('CLICK_YES_RUN')?>
                                </li>
                            </ol> 
                        </div>
                        <div class="paso">
                            <ol>
                                <li class="number">3</li>
                                <li><img src="<?= $this->site['assetsPath'] ?>/img/paso.3.png"></li>
                                <li class="descripcion"><?= $this->tr->translate('FOLLOW_INSTALLER')?>
                                </li>
                            </ol> 
                        </div>                                                        
                    </div>
                </div>                                                                  
                
            </article>
            
            <input type="hidden" name="downloadUrl" id="downloadUrl" value="<?php echo $this->downloadUrl ?>"/>
            <input type="hidden" name="downloadName" id="downloadName" value="<?php echo $this->downloadName ?>"/>
            <input type="hidden" name="signature" id="signature" value="<?php echo $this->site['signature'] ?>"/>
            <input type="hidden" name="externalBundle" id="externalBundle" value="<?= $this->externalBundle ?>"/>
            <input type="hidden" name="externalBundleUrl" id="externalBundleUrl" value="<?= $this->externalBundleUrl ?>"/>
        </div>         
    </div>

</section>



<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>