<section class="hero">
    <div class="container">
        <div class="banner">
            <?php
			if ($this->headerBanner) {
			    echo $this->showBanner($this->headerBanner, 'headerBanner');
			}
			?>
        </div>
    </div>
</section>    


<section class="main">
    <div class="container">
        <div class="content">
            
			<div id="page">
				    <div class="page__404">
			        	<h3><?= $this->tr->translate('THE SOFTWARE IS NOT FOUND') ?></h3>

						<div class="container-suggetions">
							<h4><?= $this->tr->translate('SUGGESTIONS') ?></h4>
						<ul>
							<li>
								<?= $this->tr->translate('MAKE_SURE_THAT_EVERYTHING_IS') ?>
								<span><?= $this->tr->translate('SPELLED_CORRECTLY') ?></span>
							</li>
							<li>
								<?= $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?>
								<span><?= $this->tr->translate('RECOMENDED SOFTWARE') ?>:</span>
							</li>
						</ul>
						</div>
			        </div>
			</div>

            <aside>
                <div class="banner">
                    <?= $this->showBanner($this->headerBanner, 'ad', 'header'); ?>
                </div>
                <div class="topDescargas">
                    <div class="title"><?= Zend_Registry::get('tr')->translate('TOP DOWNLOADS'); ?></div>
                    <?= $this->partialLoop('partials/front-list.phtml',  array_splice($this->topDownloads,0,3)); ?>
                </div>
            </aside>
        </div>         
    </div>

</section>




<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>