<section class="hero">
    <div class="container">
        <div class="banner">
            <?php
			if ($this->headerBanner) {
			    echo $this->showBanner($this->headerBanner, 'headerBanner');
			}
			?>
        </div>
    </div>
</section>    


<section class="main">
    <div class="container">
        <div class="content">
            
			<div id="page">
				<?php if(count($this->paginator) === 0): ?>
				    <div class="page__404">
			        	<h3><?= $this->tr->translate('NO_SEARCH_RESULTS_FOR') ?> <?= $this->search ?></h3>

						<div class="container-suggetions">
							<h4><?= $this->tr->translate('SUGGESTIONS') ?></h4>
						<ul>
							<li>
								<?= $this->tr->translate('MAKE_SURE_THAT_EVERYTHING_IS') ?>
								<span><?= $this->tr->translate('SPELLED_CORRECTLY') ?></span>
							</li>
							<li>
								<?= $this->tr->translate('TRY_TO_USE') ?>
								<span><?= $this->tr->translate('DIFERENT_OR_MORE_GENERAL_KEYWORDS') ?></span>
							</li>
							<li>
								<?= $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?>
								<span><?= $this->tr->translate('RECOMENDED SOFTWARE') ?>:</span>
							</li>
						</ul>
						</div>
			        </div>
			    <?php else: ?>
			    	<div class="software__pagination">
			            <h3><?= $this->tr->translate('SEARCH_RESULTS_FOR') ?> <?= $this->search ?></h3>
			            <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>
			        </div>
			        <ul class="software__list">
			            <?= $this->partialLoop('partials/front-list.phtml',  $this->paginator); ?>
			        </ul>
				<?php endif; ?>
			</div>

            <aside>
                <div class="banner">
                    <?= $this->showBanner($this->headerBanner, 'ad', 'header'); ?>
                </div>
                <div class="topDescargas">
                    <div class="title"><?= Zend_Registry::get('tr')->translate('TOP DOWNLOADS'); ?></div>
                    <?= $this->partialLoop('partials/front-list.phtml',  array_splice($this->topDownloads,0,3)); ?>
                </div>
            </aside>
        </div>         
    </div>

</section>




<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>