<section class="software software--blocks software--blocks--alt">
    <div class="container">
        <?php if(count($this->paginator) === 0): ?>
        <h3><?= $this->tr->translate('SOFTWARE NOT FOUND IN CATEGORY'); ?></h3>
        <?php else: ?>
        <div class="software__pagination">
            <h3><?= $this->tr->translate('SOFTWARE'); ?></h3>
            <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>
        </div>
        <?php endif; ?>

        <ul class="software__list">
            <?= $this->partialLoop('partials/front-list.phtml',  $this->paginator); ?>
        </ul>

        <?= $this->showBanner($this->footerBanner, 'ad', 'footer'); ?>
    </div>
</section>
<!-- END .software.software-blocks -->

<?= $this->partial('partials/categories.phtml', array('categories' => $this->categories)); ?>