<section class="page">
    <div class="container">
        <div class="page__404">
            <h3><?= $this->tr->translate('THE SOFTWARE IS NOT FOUND'); ?></h3>
        </div>
    </div>
</section>
<!-- END .page -->

<section class="software software--blocks software--blocks--alt">
    <div class="container">
        <h5><?= $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?> <?= $this->tr->translate('RECOMENDED SOFTWARE') ?></h5>

        <ul class="software__list">
            <?= $this->partialLoop('partials/front-list.phtml',  $this->paginator); ?>
        </ul>

        <?= $this->showBanner($this->footerBanner, 'ad', 'footer'); ?>
    </div>
</section>
<!-- END .software.software-blocks -->

<?= $this->partial('partials/categories.phtml', array('categories' => $this->categories)); ?>