<?php if(count($this->paginator) === 0): ?>
<section class="page">
    <div class="container">
        <div class="page__404">
        	<h3><?= $this->tr->translate('NO_SEARCH_RESULTS_FOR') ?> <?= $this->search ?></h3>

			<div class="container-suggetions">
				<h4><?= $this->tr->translate('SUGGESTIONS') ?></h4>
			<ul>
				<li>
					<?= $this->tr->translate('MAKE_SURE_THAT_EVERYTHING_IS') ?>
					<span><?= $this->tr->translate('SPELLED_CORRECTLY') ?></span>
				</li>
				<li>
					<?= $this->tr->translate('TRY_TO_USE') ?>
					<span><?= $this->tr->translate('DIFERENT_OR_MORE_GENERAL_KEYWORDS') ?></span>
				</li>
				<li>
					<?= $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?>
					<span><?= $this->tr->translate('RECOMENDED SOFTWARE') ?>:</span>
				</li>
			</ul>
			</div>
        </div>
    </div>
</section>
<!-- END .page -->
<?php else: ?>
<section class="software software--blocks software--blocks--alt">
    <div class="container">
        <div class="software__pagination">
            <h3><?= $this->tr->translate('SEARCH_RESULTS_FOR') ?> <?= $this->search ?></h3>
            <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>
        </div>

        <ul class="software__list">
            <?= $this->partialLoop('partials/front-list.phtml',  $this->paginator); ?>
        </ul>

        <?= $this->showBanner($this->footerBanner, 'ad', 'footer'); ?>
    </div>
</section>
<!-- END .software.software-blocks -->
<?php endif; ?>

<?= $this->partial('partials/categories.phtml', array('categories' => $this->categories)); ?>