<!DOCTYPE html>
<html lang="<?= $this->param('langCode') ?>">

    <head>
        <!-- Meta -->
        <?= $this->meta() ; ?>

        <!-- Title -->
        <?= $this->title(); ?>

        <!-- Assets -->
        <?= $this->asset('main.min.css'); ?>
        <?= $this->asset('software.min.css'); ?>
        <?= $this->asset('img/favicon.ico', array('rel' => 'icon')); ?>

        <!-- Fallback -->

        <!--[if IE 9]>
            <link href="<?php echo $this->site['assetsPath'] . '/css/main_ie9.css' ?>" rel="stylesheet">
        <![endif]-->
        <!--[if IE 6]>
            <link href="<?php echo $this->site['assetsPath'] . '/css/main_ie6.css' ?>" rel="stylesheet">
        <![endif]-->
        <!--[if IE 7]>
            <link href="<?php echo $this->site['assetsPath'] . '/css/main_ie7.css' ?>" rel="stylesheet">
        <![endif]-->
        <!--[if lt IE 10]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

        <?php echo $this->headScript()->appendFile($this->site['assetsPath'] . '/js/analytics.js') ?>
    </head>

	<body>
		<div id="wrapper">
			<nav id="header-soft">
				<div id="logo"></div>
				
			</nav>
	                <div id="categories-hidden" class="off">
	                <div id="categories-title">
	                    <ul>
	                        <?php echo $this->partialLoop('partials/categories.phtml', $this->categories); ?>
	                    </ul>
	                </div>
	              </div>
			<div class="container">
				
				<?php echo $this->layout()->content; ?>
			<div id="footer" class="bold">
					<p class="list-menu">
	 				<?php echo $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
				      </p>
	  <div class="container">
	  	<?php echo $this->action('index', 'content', null, array('section' => 'DISCLAIMER')); ?>
		</div>
				</div>
			</div> <!-- end footer download -->
		</div> <!-- end wp-->
        
        <!-- Scripts -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.cycle/3.03/jquery.cycle.all.min.js"></script>
        <?= $this->script('js/main.min.js'); ?>
        <?= $this->headScript(); ?>
        <?= $this->script(array('../common/js/main.min.js')); ?>
        <input type="hidden" id="template" value="CleanNew" />

    </body>
</html>
<!-- <?= $this->param('name'); ?> -->