<section id="content">
    <div class="content-inner">
        <div class="head-soft-thankyou">
            <h3 class="uppercase"><?php echo $this->action('index', 'content', null, array('section' => 'ERROR_MSG')); ?></h3>
        </div>
    </div>
</section>
<section id="category">
    <div class="content-inner">
        <div id="content-title-category">
            <h3><?php echo Zend_Registry::get('tr')->translate('CATEGORIES') ?></h3>
        </div>
        <ul>
            <?php echo $this->partialLoop('partials/categories.phtml', $this->categories); ?>
        </ul>
    </div>
</section>
