<div class="[ categories ]">
	<h4><?php echo $this->title; ?></h4>
	<ul class="categories__wrapper">
		<li>
			<ol class="categories__list">
				<?php $categoryCount = 0; ?>
				<?php foreach($this->categories as $category): ?>
					<?php echo $this->partial('partials/categories.phtml', $category); ?>
					<?php $categoryCount++; ?>
					<?php if($categoryCount % 5 == 0): ?>
			</ol>
		</li>
		<li>
			<ol class="categories_list">
					<?php endif; ?>
				<?php endforeach; ?>
			</ol>
		</li>
	</ul>
</div>
<!-- END .categories -->