<?php
    if(strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "chrome"))
        $instructions = array('instructions--chrome', 'arrow-chrome', 'instructions-chrome');
    elseif (strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "firefox"))
        $instructions = array('instructions--firefox', 'arrow-firefox', 'instructions-firefox');
    elseif (
        strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "trident") || 
        strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "msie"))
            $instructions = array('instructions--explorer', 'arrow-chrome', 'instructions-explorer');
    else
        $instructions = array('instructions--generic', 'arrow-chrome', 'instructions-firefox');
?>
<div id="modal"></div>
<div id="instructions" onclick="$(this).hide();$('#modal').hide();">
    <div class="instructions <?php echo $instructions[0] ?>">
        <div class="instructions__countdown">
            <?php echo Zend_Registry::get('tr')->translate('Your download will start in')?>
            <span id="countdownNumber">5</span> 
            <?php echo Zend_Registry::get('tr')->translate('seconds...'); ?>

            <div class="instructions__fallback">
                <?php echo Zend_Registry::get('tr')->translate('If the download does not start, please'); ?>
                <a href="javascript:download('<?php echo $this->download['url'] ?>', '<?php echo $this->download['file'] ?>');"><?php echo Zend_Registry::get('tr')->translate('click here'); ?></a>
            </div>
        </div>
        <!-- END .instructions__countdown -->

        <div class="instructions__steps">
            <?php
            if(strpos(strtolower($_SERVER["HTTP_USER_AGENT"]), "chrome")) {
            ?>
            <div class="instructions__steps__image">
                <img src="<?php echo $this->image($instructions[2].'.jpg'); ?>" alt="Download" />
            </div>
            <?php
            } else {
            ?>
            <img class="instructions__steps__arrow" src="<?php echo $this->image($instructions[1].'.png'); ?>" alt="Download" />
            <div class="instructions__steps__container">
                <div class="instructions__steps__image">
                    <img src="<?php echo $this->image($instructions[2].'.jpg'); ?>" alt="Download" />
                </div>
                <ul class="instructions__steps__list">
                    <li class="step1"><?php echo Zend_Registry::get('tr')->translate('Click Run or Open to begin'); ?></li>
                    <li class="step2"><?php echo Zend_Registry::get('tr')->translate('Follow our easy installation wizard'); ?></li>
                    <li class="step3"><?php echo Zend_Registry::get('tr')->translate('Enjoy your new software'); ?></li>
                </ul>
            </div>
            <?php
            }
            ?>
            <!-- END .instructions__steps__container -->
        </div>
        <!-- END .instructions__steps -->
    </div>
    <!-- END .instructions -->
</div>
<!-- END #instructions -->