<aside class="sidebar">
    <div class="sidebar__block sidebar__block--categories">
        <h4 class="sidebar__block__title"><?php echo $this->titles['categories']; ?></h4>
        <ul class="sidebar__block__menu">
            <?php echo $this->partialLoop('partials/categories.phtml', $this->data['categories']); ?>
        </ul>
    </div>
    <!-- END .sidebar__block.sidebar__block-categories -->

    <div class="sidebar__block sidebar__block--tagcloud">
        <h4 class="sidebar__block__title"><?php echo $this->titles['terms']; ?></h4>
        <ul class="sidebar__block__menu">
            <?php echo $this->partialLoop('partials/search-cloud.phtml', $this->data['terms']); ?>      
        </ul>
    </div>
    <!-- END .sidebar__block.sidebar__block-tagcloud -->

    <?php echo $this->banners['leftBottomBanner'] ? '<div class="sidebar__block sidebar__block--ad">' . $this->banners['leftBottomBanner'] . '</div>' : ''; ?>
</aside>
<!-- END .sidebar -->