<li class="software" id="software-<?php echo $this->codSoftware; ?>">
	<a href="http://<?php echo $this->baseUrl() . '/' . $this->uri; ?>" class="software__image">
		<img src="<?php echo $this->partialLoop()->view->site['assetsPath'] ?>/img/icon/<?php echo $this->codSoftware ?>.png" alt="<?php echo $this->name ?>" />
	</a>
	<div class="software__content">
		<a href="http://<?php echo $this->baseUrl() . '/' . $this->uri; ?>" class="software__name"><?php echo $this->name ?></a>
		<p class="software__excerpt">
			<?php echo $this->brief ?>
		</p>
		<a href="http://<?php echo $this->baseUrl() . '/' . $this->uri; ?>" class="software__download">
			<i class="fa fa-download"></i>
			<span><?php echo Zend_Registry::get('tr')->translate('DOWNLOAD') ?></span>
		</a>
	</div>
</li>
<!-- END #software-<?php echo $this->codSoftware; ?> -->