<!-- Safari Modal -->
<div class="DirectionsModal_sf modal-container" style="display: none;">
    <div class="modal-bg"></div>
    <div class="modal-content-container">
        <div class="modal-default">
            <div class="padding20"> 
                <span class="number one"></span>
                <h2><?php echo $this->tr->translate('STEP_ONE'); ?></h2>
                <p>
                    <?php echo $this->tr->translate('DNW_EXE'); ?>
                </p>
                <div class="clear10"></div>
                <span class="number two"></span>
                <h2><?php echo $this->tr->translate('STEP_TWO'); ?></h2>
                <p>
                    <?php echo $this->tr->translate('FOLLOW_INSTALLER'); ?>
                </p>
            </div>
            <div class="bluebar"></div>
        </div>
    </div>  
</div>
<!-- END Safari Modal -->