<!-- Firefox modal -->
<div class="DirectionsModal_ff modal-container" style="display: none; ">
    <div class="modal-bg"></div>
    <div class="modal-content-container">
        <div class="modal-ff-arrow modal-arrow"></div>
        <div class="modal-ff">
            <div class="col1">
                <h3><?php echo $this->tr->translate('STEP_ONE'); ?></h3>
                <h4><?php echo $this->tr->translate('CLICK_SAVE'); ?></h4>
            </div>
            <div class="col2">
                <h3><?php echo $this->tr->translate('STEP_TWO'); ?></h3>
                <h4>
                    <?php echo $this->tr->translate('CLICK_DWN_ABOVE'); ?>
                    <img src="<?php echo $this->site['assetsPath']?>/img/modal-ff-arrow.png" alt="Firefox" />
                </h4>
            </div>
            <div class="col1">
                <h3><?php echo $this->tr->translate('STEP_THREE'); ?></h3>
                <h4><?php echo $this->tr->translate('CLICK_DWN_FILE'); ?></h4>
            </div>
            <div class="col2">
                <h3><?php echo $this->tr->translate('STEP_FOUR'); ?></h3>
                <h4><?php echo $this->tr->translate('CLICK_YES'); ?></h4>
            </div>
            <div class="clear10"></div>
        </div>
    </div>
</div>
<!-- END Firefox Modal -->