<!-- Chrome Modal -->
<div class="DirectionsModal_cr modal-container" style="display: none; ">
    <div class="modal-bg"></div>
    <div class="modal-content-container">
        <div class="modal-chrome-arrow modal-arrow"></div>
        <div class="modal-chrome">
            <div class="col1">
                <h3><?php echo $this->tr->translate('STEP_ONE'); ?></h3>
                <h4><?php echo $this->tr->translate('CLICK_THE_BUTTON'); ?></h4>
                <h6><?php echo $this->soft->softwareUri ?>.<?php echo $this->soft->exeType ?></h6>
                <div id="loadingchrome" style="display: block;"></div>
            </div>
            <div class="col2">
                <h3><?php echo $this->tr->translate('STEP_TWO'); ?></h3>
                <h4><?php echo $this->tr->translate('CLICK_YES_RUN'); ?></h4>
            </div>
            <div class="clear20"></div>
        </div>
    </div>
</div>
<!-- END Chrome Modal -->