<!-- Internet Explorer Modal -->
<div class="DirectionsModal_ie modal-container" style="display: none;">
    <div class="modal-bg"></div>
    <div class="modal-content-container">
        <div class="modal-ie-arrow modal-arrow"></div>
        <div class="modal-ie-arrow2 modal-arrow"></div>
        <div class="modal-ie"> 
            <h4><?php echo $this->tr->translate('CLICK_RUN_SAVE'); ?></h4>                
            <div class="clear10"></div>
        </div>
    </div>  
</div>
<!-- END Internet Explorer Modal -->