<?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>

<div class="content content--homepage">

    <ul class="featured__softwares">
        <li class="software software--column software--banner" id="software-<?php echo $this->featured[0]->codSoftware ?>">
            <img src="<?php echo $this->partialLoop()->view->site['assetsPath'] ?>/img/capture/<?php echo $this->featured[0]->codSoftware; ?>-featured.png" alt="<?php echo $this->featured[0]->name; ?>" />
            <a href="http://<?php echo $this->baseUrl() . '/' . $this->featured[0]->uri; ?>" class="software__download software__download--alt">
                <i class="fa fa-download"></i>
                <span><?php echo $this->tr->translate('Download') ?></span>
            </a>
        </li>
        <?php echo $this->partialLoop('partials/front-list.phtml', array_slice($this->featured, 1, 1)); ?>
        <?php echo $this->rightTopBanner ? '<li class="software software--column adTopRight">' . $this->showBanner($this->rightTopBanner, 'rightTopBanner') . '</li>' : ''; ?>
    </ul>
    <!-- END .featured__softwares -->

    <div class="columns">
        <?php $columns = array(
            'hot_software' => array('title' => $this->tr->translate('Hot Software'), 'list' => array_slice($this->hotSoftware, 0, 5), 'color' => 'red'),
            'new_software' => array('title' => $this->tr->translate('New Software'), 'list' => array_slice($this->newSoftware, 0, 5), 'color' => 'orange'),
            'top_downloads' => array('title' => $this->tr->translate('Top Downloads'), 'list' => array_slice($this->topDownloads, 0, 5), 'color' => 'green')
            ); ?>

        <?php foreach($columns as $tag => $column): ?>
        <div class="column column--<?php echo $tag; ?>">
            <div class="column__title column__title--<?php echo $column['color']; ?>">
                <h3><?php echo $column['title']; ?></h3>
            </div>
            <ul class="column__software">
                <?php echo $this->partialLoop('partials/top-downloads.phtml', $column['list']); ?>
            </ul>    
        </div>
        <!-- END .column -->
        <?php endforeach; ?>
    </div>
    <!-- END .columns -->

    <?php echo $this->partial('partials/categories-list.phtml', array('title' => $this->tr->translate('Categories'), 'categories' => $this->categories)); ?>

</div>
<!-- END .content.content-homepage -->

<?php echo $this->footerBanner ? '<div class="ad">' . $this->showBanner($this->footerBanner, 'headerBanner') . '</div>' : ''; ?>