<!--section class="hero">
    <div class="container">
        <?//= $this->partial('partials/slider.phtml', array('data' => $this->featured, 'site' => $this->site)); ?>
        <?//= $this->showBanner($this->headerBanner, 'ad', 'header'); ?>
    </div>
</section-->

<section class="hero">
    <div class="container">
        
        <div class="banner">
            <?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>
        </div>
        <div id="slider">
            <?= $this->partial('partials/slider.phtml', array('data' => $this->featured, 'site' => $this->site)); ?>
        </div>
    </div>
</section>   
<!-- END .hero -->


<section class="main">
    <div class="container">
        <div class="content">
            
            <article>

                <div class="table">
                    <?php $columns = array(
                        'hot_software' => array('title' => $this->tr->translate('Hot Software'), 'list' => array_slice($this->hotSoftware, 0, 4)),
                        'new_software' => array('title' => $this->tr->translate('New Software'), 'list' => array_slice($this->newSoftware, 0, 4))
                        ); ?>

                    <?php foreach($columns as $tag => $column): ?>
                            <div class="title"><?php echo $column['title']; ?></div>

                           
                            <?php echo $this->partialLoop('partials/top-downloads.phtml', $column['list']); ?>
                            
                    
                    <!-- END .column -->
                    <?php endforeach; ?>
                </div>


            </article>

            <aside>
                <div class="banner">
                    <?= $this->showBanner($this->headerBanner, 'ad', 'header'); ?>
                </div>
                <div class="topDescargas">
                    <div class="title"><?= Zend_Registry::get('tr')->translate('TOP DOWNLOADS'); ?></div>
                    <?= $this->partialLoop('partials/front-list.phtml',  array_splice($this->topDownloads,0,3)); ?>
                </div>
            </aside>
        </div>         
    </div>

</section>




<!-- END .software.software-blocks -->