<?php
echo $this->headScript();
?>
<div id="content-main" class="col-md-12">
        <!-- begin column main  -->
        <?php if ( isset($this->error) ) { ?>
        <div class="col-md-12 col-center">
            <?= $this->error; ?>
        </div>

        <?php
        }
        if ( isset($this->log) ) {
            echo $this->log;
        }else{
        ?>
        <div class="col-md-12 col-center">
            <?= $this->form; ?>
        </div>
        <?php } ?>
        <div id="loading" class="col-md-12 col-center" style="visibility:hidden;"><img src="<?= $this->site['assetsPath'] ?>/img/loader.gif" alt="" /></div>
        <!-- end column main  -->
</div>