<?php
if ($this->headerBanner) {
    echo $this->showBanner($this->headerBanner, 'headerBanner');
}
?>
<div class="left">

	<div id="categories">
	    <h3 class="uppercase"><?= $this->tr->translate('Categories') ?></h3>
	    <ul>
			<?= $this->partialLoop('partials/categories.phtml', $this->categories); ?>
	    </ul>
		<div id="categories-footer"></div>
	</div>

	<div id="search-cloud">
	    <h3 class="uppercase"><?= $this->tr->translate('Top Searches') ?></h3>
	    <div class="tags">
	        <ul>
				<?= $this->partialLoop('partials/search-cloud.phtml', $this->terms); ?>
	        </ul>
			<div id="search-cloud-bottom"></div>
	    </div>
	</div>
        <?php
        if ($this->leftBottomBanner) {
            echo $this->showBanner($this->leftBottomBanner, 'leftBottomBanner');
        }?>

</div>

<div class="right">

	<div class="center-category">
     <div id="order-box">
      <p><?= $this->tr->translate('Sort By'); ?></p>
        <a href="http://<?= $this->url(array('order' => 'name'))?>" <?= ($this->varOrder=='name' || $this->varOrder=='')?'class="active"':'';?>><?= $this->tr->translate('Name'); ?></a>
        <a href="http://<?= $this->url(array('order' => 'downloads'))?>" <?= ($this->varOrder=='downloads')?'class="active"':'';?>><?= $this->tr->translate('Downloads'); ?></a>
        <a href="http://<?= $this->url(array('order' => 'rating'))?>" <?= ($this->varOrder=='rating')?'class="active"':'';?>><?= $this->tr->translate('Rating'); ?></a>
     </div>

		<?php if (count($this->paginator) === 0): ?>
        <div class="container-messages">
            <div class="message">
                <span>
                    <?= $this->tr->translate('SOFTWARE NO FOUND IN CATEGORY'); ?>
                </span>
                <span class="not-found">"<?= ($this->category == null)?'':$this->category->category; ?>"</span>
            </div>
        </div>
        <?php endif; ?>

       	<div class="list-soft promoted">
   			<ul class="front-list">
               <?php foreach( $this->paginator as $soft ): ?>
   				<li>
                    <div class="soft-item"> 
                        <a href="http://<?= $soft->uri . '.' . $this->urlSite; ?>" class="uppercase">
                            <?= $soft->name ?>
                        </a>
                        <span class="brief">
                            <?= $soft->brief ?>
                        </span>
                        <span class="rating">
                            <img src='<?= $this->site['assetsPath'] .'/img/rating-'.(ceil($soft->rating/2)).'.png'; ?>' alt='Download'>
                        </span>
                        <span class="total-download">
                          <span class="title"><?= Zend_Registry::get('tr')->translate('TOTAL DOWNLOADS') ?> :</span>
                          <?= $soft->downloads ?>
                        </span>
                    </div>
                    <div class="icon">
                        <a href="http://<?= $soft->uri . '.' . $this->urlSite; ?>">
                            <img src="<?= $this->site['assetsPath'] ?>/img/icon/<?= $soft->codSoftware ?>.png" width="64" height="64"  alt="<?= $soft->name ?>" />
                        </a>
                    </div>
                    <div class="download-btn clear">
                        <a class="btn-download-small" href="http://<?= $soft->uri . '.' . $this->urlSite; ?>"></a>
                    </div>
   				</li>
               <?php endforeach ?>
   			</ul>
        </div>
       	<div class="clear"></div>
        <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>

    </div>

	<div id="top-download">
      <?php
      if ($this->rightBanner) {
          echo $this->showBanner($this->rightBanner, 'rightTopBanner');
      }
      ?>
		<h3 class="uppercase"><?= $this->tr->translate('Top Downloads') ?></h3>

		<ul>
			<?= $this->partialLoop('partials/top-downloads.phtml', $this->topDownloads); ?>
		</ul>
	</div>
      <?php
      if ($this->rightBottomBanner) {
          echo $this->showBanner($this->rightBottomBanner, 'rightBottomBanner');
      }
      ?>
</div>

<div class="clear"></div>
<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>
