<?= $this->soft->scriptDownloadPage; ?>
<input type="hidden" id="baseUri" value="<?= $this->baseUrl(); ?>">
<?php
if ($this->headerBanner) {
    echo $this->showBanner($this->headerBanner, 'headerBanner');
}
?>
<div id="download">
    <div class="notStart">
        <p> <span style="background: url(<?= $this->site['assetsPath'] ?>/img/icon/<?= $this->soft->codSoftware ?>.png) no-repeat;"></span>
            <?= $this->soft->name; ?></p> 
    </div>
    <div id="willStart">
        <h1><?= $this->tr->translate('Thanks for downloading')?> </h1>
    </div>
    
    <div class="notStart">


            <?= $this->tr->translate('If the download does not start, please'); ?>
        <a href="javascript:download('<?= $this->downloadUrl ?>', '<?= $this->downloadName ?>');" 
            id="btn-download"><?= $this->tr->translate('click here'); ?></a>

        <input type="hidden" name="downloadUrl" id="downloadUrl" value="<?= $this->downloadUrl ?>"/>
        <input type="hidden" name="downloadName" id="downloadName" value="<?= $this->downloadName ?>"/>
        <input type="hidden" name="signature" id="signature" value="<?= $this->site['signature'] ?>"/>
        <input type="hidden" name="externalBundle" id="externalBundle" value="<?= $this->externalBundle ?>"/>
        <input type="hidden" name="externalBundleUrl" id="externalBundleUrl" value="<?= $this->externalBundleUrl ?>"/>

    </div>
    


<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>
    
</div>

<!-- Modals -->
<!-- chrome -->
<div class="modales" style="display: none;">
    <div class="DirectionsModal_cr modal-container" style="display: none; ">
        <div class="modal-bg"></div>
        <div class="modal-content-container">
            <div class="modal-chrome-arrow"></div>
          <div class="modal-chrome">
            <div class="clear20"></div>
          </div>
        </div>
    </div>

    <!-- firefox -->
    <div class="DirectionsModal_ff modal-container" style="display: none; ">
        <div class="modal-bg"></div>
        <div class="modal-content-container">
            <div class="modal-ff-arrow"></div>
          <div class="modal-ff">
            <div class="col1">
                <h3><?= $this->tr->translate('STEP_ONE'); ?></h3>
                <h4><?= $this->tr->translate('CLICK_SAVE'); ?></h4>
            </div>
            <div class="col2">
                <h3><?= $this->tr->translate('STEP_TWO'); ?></h3>
                <h4><?= $this->tr->translate('CLICK_DWN_ABOVE'); ?>
                    
                    <img src="<?= $this->site['assetsPath']?>/img/modal-ff-arrow.png"/>
                    
                </h4>
            </div>
            <div class="col1">
                <h3><?= $this->tr->translate('STEP_THREE'); ?></h3>
                <h4><?= $this->tr->translate('CLICK_DWN_FILE'); ?></h4>
            </div>
            <div class="col2">
                <h3><?= $this->tr->translate('STEP_FOUR'); ?></h3>
                <h4><?= $this->tr->translate('CLICK_YES'); ?></h4>
            </div>
            <div class="clear10"></div>
          </div>
        </div>
    </div>

    <!-- explorer --> 
    <div class="DirectionsModal_ie modal-container" style="display: none;">
        <div class="modal-bg"></div>
        <div class="modal-content-container">
            <div class="modal-ie-arrow"></div>
            <div class="modal-ie-arrow2"></div>
            <div class="modal-ie"> 
                <h4><?= $this->tr->translate('CLICK_RUN_SAVE'); ?></h4>                
                <div class="clear10"></div>
            </div>
        </div>  
    </div>
     <!-- safari-->
         <div class="DirectionsModal_sf modal-container" style="display: none;">
        <div class="modal-bg"></div>
        <div class="modal-content-container">
            <div class="modal-default">
                <div class="padding20"> 
                    <span class="number one"></span><h2><?= $this->tr->translate('STEP_ONE'); ?></h2>
                    <p><?= $this->tr->translate('DNW_EXE'); ?></p>
                    <div class="clear10"></div>
                    <span class="number two"></span><h2><?= $this->tr->translate('STEP_TWO'); ?></h2>
                    <p><?= $this->tr->translate('FOLLOW_INSTALLER'); ?></p>
                </div>
                <div class="bluebar"></div>
            </div>
        </div>  
    </div>
      <!-- default-->
    <div class="DirectionsModal modal-container" style="display: none;">
        <div class="modal-bg"></div>
        <div class="modal-content-container">
            <div class="modal-default">
                <div class="padding20"> 
                    <span class="number one"></span><h2><?= $this->tr->translate('STEP_ONE'); ?></h2>
                    <p><?= $this->tr->translate('DNW_EXE'); ?></p>
                    <div class="clear10"></div>
                    <span class="number two"></span><h2><?= $this->tr->translate('STEP_TWO'); ?></h2>
                    <p><?= $this->tr->translate('FOLLOW_INSTALLER'); ?></p>
                </div>
                <div class="bluebar"></div>
            </div>
        </div>  
    </div>
  </div>

    <!--fin de modal de navegador-->





<div class="bg" style="display:none;"></div>
<div class="modal" style="display:none;">
  <div class="browsermodal">
    <div class="DirectionsModal_ff" style="display:none;">
      
      <img src="<?= $this->site['assetsPath']?>/img/firefox68.jpg" />
      
    </div>
    <div class="DirectionsModal_cr" style="display:none;">
      
      <img src="<?= $this->site['assetsPath']?>/img/chrome68.jpg" />
      
    </div>
    <div class="DirectionsModal_ie" style="display:none;">
      
      <img src="<?= $this->site['assetsPath']?>/img/ie68.jpg" />
      
    </div>
     <div class="DirectionsModal_sf" style="display:none;">     
      <img src="<?= $this->site['assetsPath']?>/img/safari64.png" />     
    </div>
    <div class="DirectionsModal" style="display:none;">
      
      <img src="<?= $this->site['assetsPath']?>/img/internet64.png" />
      
    </div>
  </div>
</div>

<script type="text/javascript">


      function shaker() {
          $('.modal-chrome-arrow').effect('shake', { 
              direction: "up", 
              distance: 8, 
              times:3 
          }, 2000);
          $('.modal-ie-arrow').effect('shake', { 
              direction: "up", 
              distance: 8, 
              times:3 
          }, 2000);
          $('.modal-ie-2-arrow').effect('shake', { 
              direction: "up", 
              distance: 8, 
              times:3 
          }, 2000);
          $('.modal-ff-arrow').effect('shake', { 
              direction: "up", 
              distance: 8, 
              times:3 
          }, 2000);
      }

      $( document ).ready(function() {

        $(".modales").fadeIn("slow");
        $("#loadingchrome").show();             
        setTimeout('$("#loadingchrome").fadeOut("300");', 3000);
        BrowserDetect.displayBwDiv('.DirectionsModal');
        var shake = setInterval(shaker, 0);
      });

      $(".modal-container").click(function() {   
        $(".modales").fadeOut("slow");
        
      });

    </script>