<?php
if ($this->headerBanner) {
    echo $this->showBanner($this->headerBanner, 'headerBanner');
}
?>
<div class="left">

	<div id="categories">
	    <h3 class="uppercase"><?= $this->tr->translate('Categories') ?></h3>
	    <ul>
			<?= $this->partialLoop('partials/categories.phtml', $this->categories); ?>
	    </ul>
		<div id="categories-footer"></div>
	</div>

	<div id="search-cloud">
	    <h3 class="uppercase"><?= $this->tr->translate('Top Searches') ?></h3>
	    <div class="tags">
	        <ul>
				<?= $this->partialLoop('partials/search-cloud.phtml', $this->terms); ?>
	        </ul>
			<div id="search-cloud-bottom"></div>
	    </div>
	</div>
        <?php
        if ($this->leftBottomBanner) {
            echo $this->showBanner($this->leftBottomBanner, 'leftBottomBanner');
        }?>

</div>

<div class="right">

	<div class="center-search">
        <div class="container-messages">
           <div class="message">
               <span>
                <?= $this->tr->translate('THE SOFTWARE IS NOT FOUND') ?>
               </span>
           </div>
        </div>
        <div class="container-suggetions">
            <h4><?= $this->tr->translate('SUGGESTIONS') ?></h4>
            <ul>
                <li>
                    <?= $this->tr->translate('MAKE_SURE_THAT_EVERYTHING_IS') ?>
                    <span><?= $this->tr->translate('SPELLED_CORRECTLY') ?></span>
                </li>
                <li>
                    <?= $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?>
                    <span><?= $this->tr->translate('RECOMENDED SOFTWARE') ?>:</span>
                </li>
            </ul>
            <span class="others"></span>
        </div>
        <div class="list-soft promoted" id="list-new">
			<ul class="front-list">
            <?php foreach( $this->list as $soft ): ?>
				<li>
					<div class="soft-item">
					    <a href="http://<?= $this->baseUrl() . '/' . $soft->uri ; ?>" class="uppercase">
					        <?= $soft->name ?>
					    </a>
					    <span class="brief">
					        <?= $soft->brief ?>
					    </span>
					    <span class="rating">
					        <img src='<?= $this->site['assetsPath'] . '/img/rating-'.(ceil($soft->rating/2)).'.png'; ?>' alt='Download'>
					    </span>
					</div>
					<div class="icon">
					    <a href="http://<?= $this->baseUrl() . '/' . $soft->uri ; ?>">
					        <img src="<?= $this->site['assetsPath'] ?>/img/icon/<?= $soft->codSoftware ?>.png" width="64" height="64"  alt="<?= $soft->name ?>" />
					    </a>
					</div>
					<div class="download-btn clear">
					    <a class="btn-download-small" href="http://<?= $this->baseUrl() . '/' . $soft->uri ; ?>"></a>
					</div>
				</li>
            <?php endforeach ?>
			</ul>
        </div>
		<div class="clear"></div>
	</div>

	<div id="top-download">
            <?php
            if ($this->rightBanner) {
                echo $this->showBanner($this->rightBanner, 'rightTopBanner');
            }
            ?>
		<h3 class="uppercase"><?= $this->tr->translate('Top Downloads') ?></h3>

		<ul>
			<?= $this->partialLoop('partials/top-downloads.phtml', $this->topDownloads); ?>
		</ul>
	</div>
        <?php
            if ($this->rightBottomBanner) {
                echo $this->showBanner($this->rightBottomBanner, 'rightBottomBanner');
            }
            ?>
</div>

<div class="clear"></div>
<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>