<?php
if ($this->headerBanner) {
    echo $this->showBanner($this->headerBanner, 'headerBanner');
}
?>
<div class="left">

	<div id="categories">
	    <h3 class="uppercase"><?= $this->tr->translate('Categories') ?></h3>
	    <ul>
			<?= $this->partialLoop('partials/categories.phtml', $this->categories); ?>
	    </ul>
		<div id="categories-footer"></div>
	</div>

	<div id="search-cloud">
	    <h3 class="uppercase"><?= $this->tr->translate('Top Searches') ?></h3>
	    <div class="tags">
	        <ul>
				<?= $this->partialLoop('partials/search-cloud.phtml', $this->terms); ?>
	        </ul>
			<div id="search-cloud-bottom"></div>
	    </div>
	</div>
        <?php
        if ($this->leftBottomBanner) {
            echo $this->showBanner($this->leftBottomBanner, 'leftBottomBanner');
        }?>

</div>

<div class="right">
	<div class="center-search">
		<div id="order-box">
	      <p><?= $this->tr->translate('Sort By'); ?></p>
	        <a href="http://<?= $this->url(array('order' => 'name'))?>" <?= ($this->varOrder=='name' || $this->varOrder=='')?'class="active"':'';?>><?= $this->tr->translate('Name'); ?></a>
	        <a href="http://<?= $this->url(array('order' => 'downloads'))?>" <?= ($this->varOrder=='downloads')?'class="active"':'';?>><?= $this->tr->translate('Downloads'); ?></a>
	        <a href="http://<?= $this->url(array('order' => 'rating'))?>" <?= ($this->varOrder=='rating')?'class="active"':'';?>><?= $this->tr->translate('Rating'); ?></a>
	     </div>
		    <?php if ($this->hot): ?>
				<div class="container-messages">
			        <div class="message">
			            <span>
			            	<?= $this->tr->translate('NO_SEARCH_RESULTS_FOR') ?>
			            </span>
			            <span class="not-found">"<?= $this->search ?>"</span>
			        </div>
				</div>

				<div class="container-suggetions">
					<h4><?= $this->tr->translate('SUGGESTIONS') ?></h4>
					<ul>
						<li>
							<?= $this->tr->translate('MAKE_SURE_THAT_EVERYTHING_IS') ?>
							<span><?= $this->tr->translate('SPELLED_CORRECTLY') ?></span>
						</li>
						<li>
							<?= $this->tr->translate('TRY_TO_USE') ?>
							<span><?= $this->tr->translate('DIFERENT_OR_MORE_GENERAL_KEYWORDS') ?></span>
						</li>
						<li>
							<?= $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?>
							<span><?= $this->tr->translate('RECOMENDED SOFTWARE') ?>:</span>
						</li>
					</ul>
		            <span class="others"></span>
		        </div>
		    <?php else : ?>
		    	<div class="container-messages">
			        <div class="message">
			            <span>
			            	<?= $this->tr->translate('SEARCH_RESULTS_FOR') ?>
			            </span>
			            <span class="not-found">"<?= $this->search ?>"</span>
			        </div>
				</div>
		    <?php endif; ?>
		<div class="list-soft promoted" id="list-new">
			<ul class="front-list">
            <?php foreach( $this->paginator as $soft ): ?>
				<li>
					<div class="soft-item">
					    <a href="http://<?=  $this->urlSite . '/' . $soft->uri; ?>" class="uppercase">
					        <?= $soft->name ?>
					    </a>
					    <span class="brief">
					        <?= $soft->brief ?>
					    </span>
					    <span class="rating rating-<?= (ceil($soft->rating/2)) ?>">
                                            </span>
				        <span class="total-download">
				    		<span class="title"><?= Zend_Registry::get('tr')->translate('TOTAL DOWNLOADS') ?> :</span>
				    		<?= $soft->downloads ?>
				    	</span>

					</div>
					<div class="icon">
					    <a href="http://<?=  $this->urlSite . '/' . $soft->uri; ?>">
					        <img src="<?= $this->site['assetsPath'] ?>/img/icon/<?= $soft->codSoftware ?>.png" width="64" height="64"  alt="<?= $soft->name ?>" />
					    </a>
					</div>
					<div class="download-btn clear">
					    <a class="btn-download-small" href="http://<?=  $this->urlSite . '/' . $soft->uri; ?>"></a>
					</div>
				</li>
            <?php endforeach ?>
			</ul>
        </div>
        <div class="row paginator-box">
            <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>
        </div>
		<div class="clear"></div>

    </div>


	<div id="top-download">
            <?php
            if ($this->rightTopBanner) {
                echo $this->showBanner($this->rightTopBanner, 'rightTopBanner');
            }
            ?>
		<h3 class="uppercase"><?= $this->tr->translate('Top Downloads') ?></h3>

		<ul>
			<?= $this->partialLoop('partials/top-downloads.phtml', $this->topDownloads); ?>
		</ul>
	</div>
</div>

<div class="clear"></div>
<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>