<!DOCTYPE html>
<html lang="<?= $this->param('langCode') ?>">

    <head>
        <!-- Meta -->
        <?= $this->meta() ; ?>

        <!-- Title -->
        <?= $this->title(); ?>

        <!-- Assets -->
        <?= $this->asset('main.min.css'); ?>
        <?= $this->asset('img/favicon.ico', array('rel' => 'icon')); ?>

        <!-- Fallback -->
        <!--[if IE 9]><link href="<?= $this->site['assetsPath'] . '/css/main_ie9.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 6]><link href="<?= $this->site['assetsPath'] . '/css/main_ie6.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 7]><link href="<?= $this->site['assetsPath'] . '/css/main_ie7.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if lt IE 10]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

        <?php echo $this->headScript()->appendFile($this->site['assetsPath'] . '/js/analytics.js') ?>
    </head>

<body>

	<header>
		<div id="header-content">
			<div id="header-inner">
				<nav>
					<?php echo $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
				</nav>
			</div>
			<div id="logo-content">
				<a href="http://<?php echo $this->baseUrl() ?>" id="logo"></a>
			</div>
		</div>
	</header>
	<!-- content -->

	<?php echo $this->layout()->content; ?>

	<footer id="footer">
		<div class="content-inner">
			<div id="bottom-line">
				<?php echo $this->action('index', 'content', null, array('section' => 'DISCLAIMER')); ?>

				<div id="menu">
					<?php echo $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
					<a href="http://<?php echo $this->baseUrl() . '/index/sitemap'; ?>" class="right">sitemap</a>
				</div>
			</div>
		</div>
	</footer>
        
        <!-- Scripts -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>
		<?= $this->script('js/main.min.js'); ?>
        <?= $this->script(array('../common/js/jquery.cycle.min.js', '../common/js/main.min.js')); ?>
        <input type="hidden" id="template" value="Manhattan" />

    </body>
</html>
<!-- <?= $this->param('name'); ?> -->