<section id="main">

    <div id="home" class="content">

    <?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>

        <div class="box-right">

            <?php

            if ($this->rightTopBanner) {

                echo $this->showBanner($this->rightTopBanner, 'rightTopBanner');

            }

            ?>            

        </div>

        <div id="slider">

            <div id="slideshow">

                <?php foreach ( $this->featured as $featured ) { ?>

                    <div class="slide-content">

                        <div class="slide-img">

                            <img src="<?php echo $this->site['assetsPath'] . '/img/capture/' . $featured->codSoftware.'-featured.png' ?>"  alt="<?php echo $featured->name ?>" />

                            <a href="http://<?php echo $this->baseUrl() . '/'. $featured->uri; ?>" class="btn-download">DOWNLOAD</a>

                        </div>

                        <div class="slide-detail">

                            <h2><?php echo $featured->name ?></h2>

                            <p><?php echo $featured->brief ?></p>

                            <a href="http://<?php echo $this->baseUrl() . '/'. $featured->uri; ?>"></a>

                        </div>

                    </div>

                <?php } ?>

            </div>

        </div>

       

    </div>

</section>

<section id="main-soft">

    <div  class="content">

        <div class="box-left">

            <h2 class="uppercase"><?php echo $this->tr->translate('Hot Software') ?></h2>

            <?php echo $this->partialLoop('partials/front-list.phtml', array_splice($this->hotSoftware, 0, 4)); ?>

        </div>

        <div class="box-left">

            <h2 class="uppercase"><?php echo $this->tr->translate('New Software') ?></h2>

            <?php echo $this->partialLoop('partials/front-list.phtml', array_splice($this->newSoftware, 0, 4)); ?>

        </div>

        <div id="category" class="box-right">

            <h2><?php echo Zend_Registry::get('tr')->translate('CATEGORIES') ?></h2>

            <ul>

                <?php echo $this->partialLoop('partials/categories.phtml', $this->categories); ?>

            </ul>

        </div>

        <div style="clear:both"></div>

        <?php echo $this->footerBanner ? '<div class="ad">' . $this->showBanner($this->footerBanner, 'headerBanner') . '</div>' : ''; ?>

    </div>

</section>