<!DOCTYPE html>
<html lang="<?= $this->param('langCode') ?>">

    <head>
        <!-- Meta -->
        <?= $this->meta() ; ?>

        <!-- Title -->
        <?= $this->title(); ?>

        <!-- Assets -->
        <?= $this->asset('style.css'); ?>
        <?= $this->asset('img/favicon.ico', array('rel' => 'icon')); ?>

        <!-- CSS -->
        <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" />
        <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>

        <!-- Fallback -->
        <!--[if IE 9]><link href="<?= $this->site['assetsPath'] . '/css/main_ie9.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 6]><link href="<?= $this->site['assetsPath'] . '/css/main_ie6.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 7]><link href="<?= $this->site['assetsPath'] . '/css/main_ie7.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if lt IE 10]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

        <?php echo $this->headScript()->appendFile($this->site['assetsPath'] . '/js/analytics.js') ?>
    </head>

	<body>

		<header>
	    	<div class="container">
	    		<a href="http://<?= $this->baseUrl() ?>">
		            <div class="logo">
		                <img src="<?= $this->site['assetsPath'] . '/img/logo.png' ?>" />
		            </div>
		            <!--div class="textoLogo">
		                <span class="blanco">SUPER</span><span class="amarillo">SOFTWARE</span>
		            </div-->
		        </a>
	            <div class="buscador">
            		<div id="search">
						<form id="searchForm" action="http://<?= $this->baseUrl();?>/software/search" method="get" name="searchForm">
	                		<input type="text" id="buscador" placeholder="<?= $this->tr->translate('SEARCH'); ?>" />
	                		<input type="submit" class="b-search" value="" />
						</form>
					</div>
	            </div>
	            <nav>
	                <ul>
						<?= $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
					</ul>
	            </nav>
	        </div>
	    </header>

		<div id="wrapper">
			<?= $this->layout()->content; ?>
		</div>
		
	    <footer>
	        <div class="container">

	            <div class="bannerPie">
	                <?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>
	            </div>

	            <ul>
	                <?= $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
	            </ul>
	            <p><?= $this->action('index', 'content', null, array('section' => 'DISCLAIMER')); ?></p>
	        </div>
	    </footer>		
        
        <!-- Scripts -->
        <script src="<?= $this->site['assetsPath'] . '/js/jquery.min.js'; ?>"></script>
        <?= $this->script(array('../common/js/jquery.cycle.min.js', '../common/js/main.min.js')); ?>
        <input type="hidden" id="template" value="TaxiDriver" />
        <script>
            /*$(document).ready(function(){if($(".cycleSlider").size!=0){$(".cycleSlider").cycle({fx:"scrollRight",prev:".slider__controls__prev",next:".slider__controls__next",delay:-5e3,pagerAnchorBuilder:function(e,t){return'<a href="#"> </a>'}})}})*/
            $(document).ready(function() {
			    if ($(".cycleSlider").size != 0) {
			        $(".cycleSlider").cycle({
			            fx: "fade",
			            prev: ".slider__controls__prev",
			            next: ".slider__controls__next",
			            delay: -5e3,
			            pagerAnchorBuilder: function(e, t) {
			                return '<a href="#"> </a>'
			            }
			        })
			    }
			})
        </script>
    </body>
</html>
