<!DOCTYPE html>
<html lang="<?= $this->param('langCode') ?>">

    <head>
        <!-- Meta -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?= $this->meta() ; ?>

        <!-- Title -->
        <?= $this->title(); ?>

        <!-- Assets -->
        <?= $this->asset('style.css'); ?>
      

        <!-- CSS -->
        <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>
		<link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" />
		<?php echo $this->headLink()->appendStylesheet($this->site['assetsPath'] . '/css/site.css'); ?>
        <!-- Javascript -->
		<?php echo $this->headLink()->headLink( array( 'rel' => 'icon',
            'href' => $this->site['assetsPath'] .  '/img/favicon.ico', 'type' => 'image/x-icon' ));
		echo $this->headLink();


		$this->headScript()->appendFile($this->site['assetsPath'] . '/../common/js/jquery.min.js');
		$this->headScript()->appendFile($this->site['assetsPath'] . '/../common/js/jquery.cycle.min.js');
		$this->headScript()->appendFile($this->site['assetsPath'] . '/../common/js/main.min.js');
        
		
		$this->headScript()->appendFile($this->site['assetsPath'] . '/js/analytics.js');
		echo $this->headScript();
			?>
			<!-- Fallback -->
        <!--[if IE 9]><link href="<?php echo $this->site['assetsPath'] . '/css/main_ie9.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 6]><link href="<?php echo $this->site['assetsPath'] . '/css/main_ie6.css' ?>" rel="stylesheet"><![endif]-->
		<!--[if IE 7]><link href="<?php echo $this->site['assetsPath'] . '/css/main_ie7.css' ?>" rel="stylesheet"><![endif]-->
        <!--[if lt IE 10]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    </head>

	<body>
		<header>
	    	<div class="container">
	    		<a href="http://<?= $this->baseUrl() ?>">
		            <div class="logo">
		                <img src="<?= $this->site['assetsPath'] . '/img/logo.png' ?>" />
		            </div>
		            <!--div class="textoLogo">
		                <span class="blanco">SUPER</span><span class="amarillo">SOFTWARE</span>
		            </div-->
		        </a>
	            <div class="buscador">
            		<div id="search">
						<form id="searchForm" action="http://<?= $this->baseUrl();?>/software/search" method="get" name="searchForm">
	                		<input type="text" id="buscador" placeholder="<?= $this->tr->translate('SEARCH'); ?>" />
	                		<input type="submit" class="b-search" value="" />
						</form>
					</div>
	            </div>
	            <nav>
	                <ul>
						<?= $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
					</ul>
	            </nav>
	        </div>
	    </header>

		<div id="wrapper">
		    <section class="hero">
		        <div class="container">
		            <div class="banner">
		                <?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>
		            </div>
		            <?= $this->layout()->content; ?>
		        </div>
		    </section>  
	     
			

		</div>
		
	    <footer>
	        <div class="container">

	            <div class="bannerPie">
	                <?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>
	            </div>

	            <ul>
	                <?= $this->partialLoop('partials/pages-menu.phtml', $this->pages); ?>
	            </ul>
	            <p><?= $this->action('index', 'content', null, array('section' => 'DISCLAIMER')); ?></p>
	        </div>
	    </footer>		
        
     

        <input type="hidden" id="template" value="TaxiDriver" />
        <script>
            $(document).ready(function(){
           	
            	if ($("#software-detail-text").length > 0) {
			        if ($("#software-detail-text")[0].scrollHeight - $("#software-detail-readmore").height() > $("#software-detail-text").height()) {
			            $("#software-detail-readmore").show()
			        } else {
			            $("#readmore").hide()
			        }
			    }
			    $("#software-detail-readless").hide();
			    var r = true;
			    var i = $("#software-detail-text").height();
			    $("#readmore").click(function() {
			        if (r) {
			            $("#software-detail-text").height($("#software-detail-text")[0].scrollHeight);
			            $("#software-detail-text").css({
			                overflow: "visible"
			            });
			            $("#software-detail-readmore").hide();
			            $("#software-detail-readless").show();
			            r = false
			        } else {
			            $("#software-detail-text").height(i);
			            $("#software-detail-text").css({
			                overflow: "hidden"
			            });
			            $("#software-detail-readmore").show();
			            $("#software-detail-readless").hide();
			            r = true
			        }
			    });
			    $("#readless").click(function() {
			        if (r) {
			            $("#software-detail-text").height($("#software-detail-text")[0].scrollHeight);
			            $("#software-detail-text").css({
			                overflow: "visible"
			            });
			            $("#software-detail-readless").show();
			            $("#software-detail-readmore").hide();
			            r = false
			        } else {
			            $("#software-detail-text").height(i);
			            $("#software-detail-text").css({
			                overflow: "hidden"
			            });
			            $("#software-detail-readless").hide();
			            $("#software-detail-readmore").show();
			            r = true
			        }
			    })
            })
        </script>
    </body>
</html>
<!-- <?= $this->param('name'); ?> -->