<div class="slider">
	<div class="slider__controls">
		<a href="#" class="slider__controls__next"><i class="fa fa-chevron-right"></i></a>
		<a href="#" class="slider__controls__prev"><i class="fa fa-chevron-left"></i></a>
	</div>
	<!-- END .slider__controls -->

	<ul class="slider__slides cycleSlider">
		<?php foreach($this->data as $software): ?>
		<li class="slider__slide" id="software-slide-<?= $software->codSoftware; ?>">
			<div class="slider__slide__wrapper">
				<div class="slider__slide__container">
					<div class="slider__slide__icon">
						<img src="<?= $this->software('icon', $software); ?>" alt="<?= $software->name; ?>" height="64" width="64" />
					</div>
					<div class="slider__slide__content">
						<div class="slider__slide__title">
							<h2><?= $software->name; ?></h2>
						</div>
						<p class="slider__slide__brief">
							<?= $software->brief; ?>
						</p>
					</div>
				</div>
				<div class="slider__slide__download">
					<a href="<?= $this->software('permalink', $software); ?>" class="slider__slide__download__btn">
						<i class="fa fa-angle-double-down"></i>
						<span><?= Zend_Registry::get('tr')->translate('DOWNLOAD'); ?></span>
					</a>
				</div>
			</div>
		</li>
		<!-- END #software-<?= $software->codSoftware; ?> -->
		<?php endforeach; ?>
	</ul>
	<!-- END .slider__slides -->
</div>
<!-- END .slider -->