<div class="main main--page">
    <?php echo $this->partial('partials/sidebar.phtml', array(
        'titles' => array(
            'categories' => $this->tr->translate('Categories'),
            'terms' => $this->tr->translate('Top Searches'),
            ),
        'data' => array(
            'categories' => $this->categories,
            'terms' => $this->terms,
            ),
        'banners' => array()
    )); ?>

	<section class="page">

		<?php if($this->image): ?>
		<figure class="page__image">
			<img src="<?php echo $this->image; ?>" alt="<?php echo $this->title;?>" />
		</figure>
		<?php endif; ?>

		<h2 class="page__title"><?php echo $this->tr->translate('CONTACT_FORM') ?></h2>

		<div class="page__content">
		<?php if ( isset($this->form) ) echo $this->form ?>

		<?php if ( isset($this->successMail) ): ?>
			<div class="message">
				<span> <?php echo $this->successMail ?></span>
			</div>
		<?php endif ?>
		</div>

	</section>
	<!-- END .page -->
</div>
<!-- END .content -->
