<section id="software-list">

    <div class="content-inner">

        <?php

        if ($this->rightBanner) {

            echo $this->showBanner($this->rightBanner, 'rightBanner');

        }

        ?>

        <div id="content-title-result">

            <?php if (count($this->paginator) === 0) { ?>

                <h3><?php echo $this->tr->translate('SOFTWARE NOT FOUND IN CATEGORY'); ?></h3>

            <?php } else { ?>

                <h3><?php echo $this->tr->translate('SOFTWARE'); ?></h3>

            <?php } ?>

        </div>

        <div class="list-soft promoted" id="list-new">

            <ul class="front-list">

            <?php foreach( $this->paginator as $soft ): ?>

                <li>

                    <div class="icon">

                        <a href="http://<?php echo  $this->urlSite . '/' . $soft->uri; ?>">

                            <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $soft->codSoftware ?>.png" width="64" height="64"  alt="<?php echo $soft->name ?>" />

                        </a>

                    </div>

                    <div class="soft-item">

                        <a href="http://<?php echo $this->urlSite . '/' . $soft->uri; ?>" class="uppercase">

                            <?php echo $soft->name ?>

                        </a>

                        <span class="brief">

                            <?php echo $soft->brief ?>

                        </span>

                        <div class="download-btn clear">

                            <a class="btn-download-small" href="http://<?php echo $this->urlSite . '/' . $soft->uri; ?>">

                                <?php echo $this->tr->translate('Download') ?>

                            </a>

                        </div>

                    </div>

                </li>

            <?php endforeach ?>

            </ul>

        </div>

        <div class="paginator-box">

            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>

        </div>

        <div class="clear"></div>

    </div>

</section>

