<section id="software-list">
    <div class="content-inner">

    	<!-- <div id="order-box">
	      <p><?php echo $this->tr->translate('Sort By'); ?></p>
	        <a href="http://<?php echo $this->url(array('order' => 'name'))?>" <?php echo ($this->varOrder=='name' || $this->varOrder=='')?'class="active"':'';?>><?php echo $this->tr->translate('Name'); ?></a>
	        <a href="http://<?php echo $this->url(array('order' => 'downloads'))?>" <?php echo ($this->varOrder=='downloads')?'class="active"':'';?>><?php echo $this->tr->translate('Downloads'); ?></a>
	        <a href="http://<?php echo $this->url(array('order' => 'rating'))?>" <?php echo ($this->varOrder=='rating')?'class="active"':'';?>><?php echo $this->tr->translate('Rating'); ?></a>
	     </div> -->

		    <?php if ($this->hot): ?>
		    <div id="content-title-result">
					<h3><?php echo $this->tr->translate('NO_SEARCH_RESULTS_FOR') ?> "<?php echo $this->search ?>"</h3>
				</div>
		
				<div class="container-suggetions">
					<h4><?php echo $this->tr->translate('SUGGESTIONS') ?></h4>
					<ul>
						<li>
							<?php echo $this->tr->translate('MAKE_SURE_THAT_EVERYTHING_IS') ?>
							<span><?php echo $this->tr->translate('SPELLED_CORRECTLY') ?></span>
						</li>
						<li>
							<?php echo $this->tr->translate('TRY_TO_USE') ?>
							<span><?php echo $this->tr->translate('DIFERENT_OR_MORE_GENERAL_KEYWORDS') ?></span>
						</li>
						<li>
							<?php echo $this->tr->translate('MAYBE_YOU_ARE_INTERESTED_IN_THESE') ?>
							<span><?php echo $this->tr->translate('RECOMENDED SOFTWARE') ?>:</span>
						</li>
					</ul>
		            <span class="others"></span>
		        </div>
		    <?php else : ?>
		   <div id="content-title-result">
					<h3><?php echo $this->tr->translate('NO_SEARCH_RESULTS_FOR') ?> "<?php echo $this->search ?>"</h3>
				</div>
		    <?php endif; ?>
		    <div class="list-soft promoted" id="list-new">
			<ul class="front-list">
            <?php foreach( $this->paginator as $soft ): ?>
				<li>
					<div class="icon">
					    <a href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>">
					        <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $soft->codSoftware ?>.png" width="64" height="64"  alt="<?php echo $soft->name ?>" />
					    </a>
					</div>
					<div class="soft-item">
					    <a href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>" class="uppercase">
					        <?php echo $soft->name ?>
					    </a>
					    <span class="brief">
					        <?php echo $soft->brief ?>
					    </span>
						<div class="download-btn clear">
					    <a class="btn-download-small" href="http://<?php echo $soft->uri . '.' . $this->urlSite; ?>"><?php echo $this->tr->translate('Download') ?></a>
						</div>
					</div>
					
					
				</li>
            <?php endforeach ?>
			</ul>
        </div>
        <div class="paginator-box">
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>
        </div>
		<div class="clear"></div>

    </div>

    </div>
 </section>   	