<section class="hero">
    <div class="container">
        <div class="banner">
            <?php
            if ($this->headerBanner) {
                echo $this->showBanner($this->headerBanner, 'headerBanner');
            }
            ?>
        </div>
    </div>
</section>    
<section class="main">
    <div class="container">
        <div class="content">     
            <div id="page"> 
                <p><?php echo $this->tr->translate('Sorry, the page you are looking for cannot be found!'); ?></p>
            </div>

            <aside>
                <div class="topDescargas landing">
                    <div class="title"><?= Zend_Registry::get('tr')->translate('TOP DOWNLOADS'); ?></div>
                    <?= $this->partialLoop('partials/front-list.phtml',  array_splice($this->topDownloads,0,3)); ?>
                    <div class="box">
                        <img src="<?= $this->showBanner($this->footerBanner, 'ad', 'footer'); ?>" />
                    </div>   
                </div>      
            </aside>
        </div>         
    </div>

</section>
<!-- END .content -->

<?php echo $this->footerBanner ? '<div class="ad">' . $this->showBanner($this->footerBanner, 'headerBanner') . '</div>' : ''; ?>