<section class="hero">
    <div class="container">
        <div class="banner">
            <?php
			if ($this->headerBanner) {
			    echo $this->showBanner($this->headerBanner, 'headerBanner');
			}
			?>
        </div>
        <div class="main">
            <div class="content">     
                <div id="page"> 
                    <?= $this->content;?>
                </div>

                <aside>
                    <div class="topDescargas landing">
                        <div class="title"><?= Zend_Registry::get('tr')->translate('TOP DOWNLOADS'); ?></div>
                        <?= $this->partialLoop('partials/front-list.phtml',  array_splice($this->topDownloads,0,3)); ?>
                        <div class="box">
                            <img src="<?= $this->showBanner($this->footerBanner, 'ad', 'footer'); ?>" />
                        </div>   
                    </div>      
                </aside>
            </div>         
        </div>
    </div>    
</section>    


<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>
