
<section id="main-content">
    <div class="content" id="page">
        <?php
if ($this->headerBanner) {
  echo '<div class="ad">' .$this->showBanner($this->headerBanner, 'headerBanner'). '</div>';
}
?>
        <div class="box-left">
            <div id="page">
                <?php if ($this->image != '') { ?>
                    <img src="<?php echo $this->image ?>" />
                <?php } ?>
                <?php echo $this->content;?>
            </div>
        </div>
        <div id="category" class="box-right">
            <h2><?php echo Zend_Registry::get('tr')->translate('CATEGORIES') ?></h2>
            <ul>
                <?php echo $this->partialLoop('partials/categories.phtml', $this->categories); ?>
            </ul>
        </div>
        <div class="clearboth"></div>

        <?php
if ($this->footerBanner) {
     echo '<div class="ad">' . $this->showBanner($this->footerBanner, 'footerBanner') .'</div>';
}
?>  
    </div>
</section>
