<?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>

<div class="main main--category">
    <?php echo $this->partial('partials/sidebar.phtml', array(
        'titles' => array(
            'categories' => $this->tr->translate('Categories'),
            'terms' => $this->tr->translate('Top Searches'),
            ),
        'data' => array(
            'categories' => $this->categories,
            'terms' => $this->terms,
            ),
        'banners' => array(
            'leftBottomBanner' => $this->leftBottomBanner ? $this->showBanner($this->leftBottomBanner, 'leftBottomBanner') : false
            )
    )); ?>

    <section class="category">
        <?php if(count($this->paginator) === 0): ?>
        <div class="message message--software-not-found">
            <div class="message__content">
                <i class="fa fa-frown-o"></i>
                <div>
                    <p><?php echo $this->tr->translate('We couldn\'t find any software under'); ?> <?php echo $this->category->category; ?></p>
                </div>
            </div>
            <div class="topDownloads">
                <h4><?php echo $this->tr->translate('You might also be interested in..'); ?></h4>
                <ul class="topDownloads__list">
                    <?php echo $this->partialLoop('partials/top-downloads.phtml', $this->topDownloads); ?>
                </ul>
            </div>
        </div>
        <!-- END .message.message-software-not-found -->
        <?php else: ?>
        <h2 class="category__title"><?php echo $this->category->category; ?></h2>

        <ul class="category__filters">
            <li class="category__filters__title"><i class="fa fa-filter"></i> <?php echo $this->tr->translate('Sort By'); ?></li>
            <li<?php echo ($this->varOrder=='name' || $this->varOrder=='')?' class="active"':'';?>><a href="http://<?php echo $this->url(array('order' => 'name'))?>"><?php echo $this->tr->translate('Name'); ?></a></li>
            <li<?php echo ($this->varOrder=='downloads')?' class="active"':'';?>><a href="http://<?php echo $this->url(array('order' => 'downloads'))?>" ><?php echo $this->tr->translate('Downloads'); ?></a></li>
            <li<?php echo ($this->varOrder=='rating')?' class="active"':'';?>><a href="http://<?php echo $this->url(array('order' => 'rating'))?>" ><?php echo $this->tr->translate('Rating'); ?></a></li>
        </ul>
        <!-- END .category__filters -->

        <ul class="software-listings">
            <?php foreach($this->paginator as $software): ?>
            <li class="software-listing" id="software-<?php echo $software->codSoftware; ?>">
                <div class="software-listing__icon">
                    <a href="http://<?php echo $this->urlSite . '/' . $software->uri; ?>">
                        <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $software->codSoftware ?>.png" alt="<?php echo $software->name ?>" />
                    </a>
                </div>
                <div class="software-listing__information">
                    <h3 class="software-listing__title"> 
                        <a href="http://<?php echo $this->urlSite . '/' . $software->uri; ?>" class="uppercase"><?php echo $software->name ?></a>
                        <span class="software-listing__rating software-listing__rating--<?php echo ceil($software->rating / 2); ?>"></span>
                    </h3>
                    <p class="software-listing__brief">
                        <?php echo $software->brief ?>                
                    </p>
                    <div class="software-listing__download">
                        <a class="software-listing__download__btn" href="http://<?php echo $this->urlSite . '/' . $software->uri; ?>">
                            <i class="fa fa-download"></i> 
                            <?php echo $this->tr->translate('Download'); ?>
                        </a>
                        <div class="software-listing__download__count">
                            <?php echo $software->downloads; ?> <span><?php echo $this->tr->translate('Downloads') ?></span>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
        <!-- END .software-list -->

        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml'); ?>
        <?php endif; ?>
    </section>
    <!-- END .category -->

</div>
<!-- END .content -->

<?php echo $this->footerBanner ? '<div class="ad">' . $this->showBanner($this->footerBanner, 'headerBanner') . '</div>' : ''; ?>