<?php echo $this->soft->scriptDownloadPage; ?>

<?php echo $this->partial('partials/modal.phtml', array('download' => array('url' => $this->downloadUrl, 'file' => $this->downloadName))); ?>

<input type="hidden" id="baseUri" value="<?php echo $this->baseUrl(); ?>">

<?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>

<div class="main main--download">
    
    <section class="download">
        <div class="download__content">
            <div class="download__icon">
                <i class="fa fa-cloud-download"></i>
                <img src="<?php echo $this->site['assetsPath'] ?>/img/icon/<?php echo $this->soft->codSoftware ?>.png" alt="<?php echo $this->soft->name; ?>">
            </div>

            <h2><?php echo $this->tr->translate('Thanks for downloading')?> <?php echo $this->soft->name; ?></h2>


            <div class="download__fallback">
                <?php echo $this->tr->translate('If the download does not start, please'); ?>
                <a href="javascript:download('<?php echo $this->downloadUrl ?>', '<?php echo $this->downloadName ?>');" id="btn-download"><?php echo $this->tr->translate('click here'); ?></a>

                <input type="hidden" name="downloadUrl" id="downloadUrl" value="<?php echo $this->downloadUrl ?>"/>
                <input type="hidden" name="downloadName" id="downloadName" value="<?php echo $this->downloadName ?>"/>
                <input type="hidden" name="signature" id="signature" value="<?php echo $this->site['signature'] ?>"/>
                <input type="hidden" name="externalBundle" id="externalBundle" value="<?= $this->externalBundle ?>"/>
                <input type="hidden" name="externalBundleUrl" id="externalBundleUrl" value="<?= $this->externalBundleUrl ?>"/>
            </div>
        </div>
    </section>
    <!-- END .download -->

</div>
<!-- END .main.main-download -->

<?php echo $this->footerBanner ? '<div class="ad">' . $this->showBanner($this->footerBanner, 'headerBanner') . '</div>' : ''; ?>




