<?php echo $this->software->scriptThankyouPage; ?>
<?php echo $this->headerBanner ? '<div class="ad">' . $this->showBanner($this->headerBanner, 'headerBanner') . '</div>' : ''; ?>

<div class="main main--category">
    <?php echo $this->partial('partials/sidebar.phtml', array(
        'titles' => array(
            'categories' => $this->tr->translate('Categories'),
            'terms' => $this->tr->translate('Top Searches'),
            ),
        'data' => array(
            'categories' => $this->categories,
            'terms' => $this->terms,
            ),
        'banners' => array(
            'leftBottomBanner' => $this->leftBottomBanner ? $this->showBanner($this->leftBottomBanner, 'leftBottomBanner') : false
            )
    )); ?>

    <section class="category">
        <div class="message message--success">
            <div class="message__content">
                <i class="fa fa-smile-o"></i>
                <div>
                    <h3><?php echo $this->software->name ?></h3>
                    <p><?php echo $this->tr->translate('THANK YOU PAGE') ?></p>
                </div>
            </div>
            <div class="topDownloads">
                <h4><?php echo $this->tr->translate('You might also be interested in..'); ?></h4>
                <ul class="topDownloads__list">
                    <?php echo $this->partialLoop('partials/top-downloads.phtml', $this->topDownloads); ?>
                </ul>
            </div>
        </div>
        <!-- END .message.message-software-not-found -->
    </section>
    <!-- END .category -->

</div>
<!-- END .content -->

<?php echo $this->footerBanner ? '<div class="ad">' . $this->showBanner($this->footerBanner, 'headerBanner') . '</div>' : ''; ?>