<script>
function shaker() {
    $('.modal-chrome-arrow').effect('shake', { 
        direction: "up", 
        distance: 8, 
        times:3 
    }, 2000);
    $('.modal-ie-arrow').effect('shake', { 
        direction: "up", 
        distance: 8, 
        times:3 
    }, 2000);
    $('.modal-ie-2-arrow').effect('shake', { 
        direction: "up", 
        distance: 8, 
        times:3 
    }, 2000);
    $('.modal-ff-arrow').effect('shake', { 
        direction: "up", 
        distance: 8, 
        times:3 
    }, 2000);
}

$( document ).ready(function() {

  $(".modales").fadeIn("slow");
  $("#loadingchrome").show();             
  setTimeout('$("#loadingchrome").fadeOut("300");', 3000);
  BrowserDetect.displayBwDiv('.DirectionsModal');
  var shake = setInterval(shaker, 0);
});

$(".modal-container").click(function() {   
  $(".modales").fadeOut("slow");
  
});
</script>