<li>
    <div class="soft-item">
		<a href="http://<?= $this->baseUrl() . '/' . $this->uri; ?>" class="uppercase">
			<?= $this->name ?>
		</a>
		<span class="brief">
			<?= $this->brief ?>
		</span>
		<span class="rating rating-<?= (ceil($this->rating/2)) ?>">
		</span>
	    <span class="total-download">
			<span class="title"><?= Zend_Registry::get('tr')->translate('TOTAL DOWNLOADS') ?> :</span>
			<?= $this->downloads ?>
		</span>
	</div>
	<div class="icon">
		<a href="http://<?= $this->baseUrl() . '/' . $this->uri; ?>">
			<img src="<?= $this->partialLoop()->view->site['assetsPath'] ?>/img/icon/<?= $this->codSoftware ?>.png" width="64" height="64"  alt="<?= $this->name ?>" />
		</a>
	</div>
	<div class="download-btn clear">
		<a class="btn-download-small" href="http://<?= $this->baseUrl() . '/' . $this->uri; ?>"></a>
    </div>
</li>