<li>
	<div class="icon">
		<a class="name" href="http://<?= $this->baseUrl() . '/' . $this->uri; ?>">
			<img src="<?= $this->partialLoop()->view->site['assetsPath'] ?>/img/icon/<?= $this->codSoftware ?>.png" width="48" height="48" alt="<?= $this->name ?>"/>
		</a>
	</div>
    <div class="name">
        <a class="name" href="http://<?= $this->baseUrl() . '/' . $this->uri; ?>">
    		<?= $this->name ?>
    	</a>
    </div>
	<div class="download-btn-lite">
		<a class="btn-download-icon" href="http://<?= $this->baseUrl() . '/' . $this->uri; ?>"></a>
	</div>

</li>
