<div class="left">

	<div id="categories">
	    <h3 class="uppercase"><?= $this->tr->translate('Categories') ?></h3>
	    <ul>
			<?= $this->partialLoop('partials/categories.phtml', $this->categories); ?>
	    </ul>
		<div id="categories-footer"></div>
	</div>

	<div id="search-cloud">
	    <h3 class="uppercase"><?= $this->tr->translate('Top Searches') ?></h3>
	    <div class="tags">
	        <ul>
				<?= $this->partialLoop('partials/search-cloud.phtml', $this->terms); ?>
	        </ul>
			<div id="search-cloud-bottom"></div>
	    </div>
	</div>
        <?php
        if ($this->leftBottomBanner) {
            echo $this->showBanner($this->leftBottomBanner, 'leftBottomBanner');
        }?>

</div>

<div class="right">

	<div class="page">
		<h3><?= $this->tr->translate('CONTACT_FORM') ?></h3>
		<?php if ( isset($this->form) ) echo $this->form ?>

		<?php if ( isset($this->successMail) ): ?>
			<div class="message">
				<span> <?= $this->successMail ?></span>
			</div>
		<?php endif ?>

	</div>

	<div class="clear"></div>
</div>
<div class="clear"></div>