<?php
if ($this->headerBanner) {
    echo $this->showBanner($this->headerBanner, 'headerBanner');
}
?>
<div class="left">

	<div id="categories">
	    <h3 class="uppercase"><?= $this->tr->translate('Categories') ?></h3>
	    <ul>
			<?= $this->partialLoop('partials/categories.phtml', $this->categories); ?>
	    </ul>
		<div id="categories-footer"></div>
	</div>

	<div id="search-cloud">
	    <h3 class="uppercase"><?= $this->tr->translate('Top Searches') ?></h3>
	    <div class="tags">
	        <ul>
				<?= $this->partialLoop('partials/search-cloud.phtml', $this->searchTerms); ?>
	        </ul>
			<div id="search-cloud-bottom"></div>
	    </div>
	</div>
        <?php
        if ($this->leftBottomBanner) {
            echo $this->showBanner($this->leftBottomBanner, 'leftBottomBanner');
        }?>

</div>

<div class="right">

	<div class="center">

		<div id="slider">
			<a href="#" class="slider-next" id="next"></a>
   			<a href="#" class="slider-previous" id="prev"></a>
   			<div class="featured"></div>
		    <div id="slideshow">
    		    <?php foreach ( $this->featured as $featured ) { ?>
    		    <div>
                    <a href="http://<?= $this->baseUrl() . '/' . $featured->uri; ?>">
                    	<img src="<?= $this->site['assetsPath'] . '/img/capture/' . $featured->codSoftware.'-featured.png' ?>"  alt="<?= $featured->name ?>"/>
                    </a>
                    <div class="textbox" style="position: absolute; top: 220px;">
                    <h3><a href="http://<?= $this->baseUrl() . '/' . $featured->uri; ?>" class="name"><?= $featured->name ?></a></h3>

                    <div class="slider-btn">
                    	<a class="btn-download-small" href="http://<?= $this->baseUrl() . '/' . $featured->uri; ?>"></a>
                    </div>
                    <br>
                    <p><?= $featured->brief ?></p>
                </div>
                    </div>
                <?php } ?>
            </div>
        </div>
        

        <div class="list-soft" id="promoted-tabs">
        	<button type="button" id="tab-button-hot" class="tab-button tab-button-active uppercase" onclick="showHotSoftware();">
				<?= $this->tr->translate('Hot Software') ?>
			</button>
            <button type="button" id="tab-button-new" class="tab-button tab-button-inactive uppercase" onclick="showNewSoftware();">
				<?= $this->tr->translate('New Software') ?>
			</button>
        </div>

        <div class="list-soft promoted" id="list-hot">
			<ul class='front-list'>
				<?= $this->partialLoop('partials/front-list.phtml', $this->hotSoftware); ?>
			</ul>
        </div>

        <div class="list-soft promoted" id="list-new" style="display:none">
			<ul class='front-list'>
				<?= $this->partialLoop('partials/front-list.phtml', $this->newSoftware); ?>
			</ul>
        </div>

	</div>
        <div id="top-download">
            <?php
            if ($this->rightTopBanner) {
                echo $this->showBanner($this->rightTopBanner, 'rightTopBanner');
            }
            ?>
		<h3 class="uppercase"><?= $this->tr->translate('Top Downloads') ?></h3>

		<ul>
			<?= $this->partialLoop('partials/top-downloads.phtml', $this->topDownloads); ?>
		</ul>
                
            
	</div>
	<?php
    if ($this->rightBottomBanner) {
            echo $this->showBanner($this->rightBottomBanner, 'rightBottomBanner');
    } else {
    ?>
    <div class="clear"></div>
    <?php } ?>

	<div class="clear"></div>

</div>
<div class="clear"></div>
<?php
if ($this->footerBanner) {
    echo $this->showBanner($this->footerBanner, 'footerBanner');
}
?>
